// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_service.proto

package nvidia_inferenceserver

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//@@  .. cpp:enum:: Type
//@@
//@@     Types of control operation
//@@
type ModelControlRequest_Type int32

const (
	//@@    .. cpp:enumerator:: Type::UNLOAD = 0
	//@@
	//@@       To unload the specified model.
	//@@
	ModelControlRequest_UNLOAD ModelControlRequest_Type = 0
	//@@    .. cpp:enumerator:: Type::LOAD = 1
	//@@
	//@@       To load the specified model. If the model has been loaded,
	//@@       it will be reloaded to fetch the latest change.
	//@@
	ModelControlRequest_LOAD ModelControlRequest_Type = 1
)

var ModelControlRequest_Type_name = map[int32]string{
	0: "UNLOAD",
	1: "LOAD",
}

var ModelControlRequest_Type_value = map[string]int32{
	"UNLOAD": 0,
	"LOAD":   1,
}

func (x ModelControlRequest_Type) String() string {
	return proto.EnumName(ModelControlRequest_Type_name, int32(x))
}

func (ModelControlRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{4, 0}
}

//@@
//@@.. cpp:var:: message StatusRequest
//@@
//@@   Request message for Status gRPC endpoint.
//@@
type StatusRequest struct {
	//@@
	//@@  .. cpp:var:: string model_name
	//@@
	//@@     The specific model status to be returned. If empty return status
	//@@     for all models.
	//@@
	ModelName            string   `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{0}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

func (m *StatusRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

//@@
//@@.. cpp:var:: message StatusResponse
//@@
//@@   Response message for Status gRPC endpoint.
//@@
type StatusResponse struct {
	//@@
	//@@  .. cpp:var:: RequestStatus request_status
	//@@
	//@@     The status of the request, indicating success or failure.
	//@@
	RequestStatus *RequestStatus `protobuf:"bytes,1,opt,name=request_status,json=requestStatus,proto3" json:"request_status,omitempty"`
	//@@
	//@@  .. cpp:var:: ServerStatus server_status
	//@@
	//@@     The server and model status.
	//@@
	ServerStatus         *ServerStatus `protobuf:"bytes,2,opt,name=server_status,json=serverStatus,proto3" json:"server_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{1}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetRequestStatus() *RequestStatus {
	if m != nil {
		return m.RequestStatus
	}
	return nil
}

func (m *StatusResponse) GetServerStatus() *ServerStatus {
	if m != nil {
		return m.ServerStatus
	}
	return nil
}

//@@
//@@.. cpp:var:: message HealthRequest
//@@
//@@   Request message for Health gRPC endpoint.
//@@
type HealthRequest struct {
	//@@
	//@@  .. cpp:var:: string mode
	//@@
	//@@     The requested health action: 'live' requests the liveness
	//@@     state of the inference server; 'ready' requests the readiness state
	//@@     of the inference server.
	//@@
	Mode                 string   `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{2}
}

func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

func (m *HealthRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

//@@
//@@.. cpp:var:: message HealthResponse
//@@
//@@   Response message for Health gRPC endpoint.
//@@
type HealthResponse struct {
	//@@
	//@@  .. cpp:var:: RequestStatus request_status
	//@@
	//@@     The status of the request, indicating success or failure.
	//@@
	RequestStatus *RequestStatus `protobuf:"bytes,1,opt,name=request_status,json=requestStatus,proto3" json:"request_status,omitempty"`
	//@@
	//@@  .. cpp:var:: bool health
	//@@
	//@@     The result of the request. True indicates the inference server is
	//@@     live/ready, false indicates the inference server is not live/ready.
	//@@
	Health               bool     `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{3}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetRequestStatus() *RequestStatus {
	if m != nil {
		return m.RequestStatus
	}
	return nil
}

func (m *HealthResponse) GetHealth() bool {
	if m != nil {
		return m.Health
	}
	return false
}

//@@
//@@.. cpp:var:: message ModelControlRequest
//@@
//@@   Request message for ModelControl gRPC endpoint.
//@@
type ModelControlRequest struct {
	//@@
	//@@  .. cpp:var:: string model_name
	//@@
	//@@     The target model name.
	//@@
	ModelName string `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	//@@
	//@@  .. cpp:var:: Type type
	//@@
	//@@     The control type that is operated on the specified model.
	//@@
	Type                 ModelControlRequest_Type `protobuf:"varint,2,opt,name=type,proto3,enum=nvidia.inferenceserver.ModelControlRequest_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ModelControlRequest) Reset()         { *m = ModelControlRequest{} }
func (m *ModelControlRequest) String() string { return proto.CompactTextString(m) }
func (*ModelControlRequest) ProtoMessage()    {}
func (*ModelControlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{4}
}

func (m *ModelControlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelControlRequest.Unmarshal(m, b)
}
func (m *ModelControlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelControlRequest.Marshal(b, m, deterministic)
}
func (m *ModelControlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelControlRequest.Merge(m, src)
}
func (m *ModelControlRequest) XXX_Size() int {
	return xxx_messageInfo_ModelControlRequest.Size(m)
}
func (m *ModelControlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelControlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModelControlRequest proto.InternalMessageInfo

func (m *ModelControlRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *ModelControlRequest) GetType() ModelControlRequest_Type {
	if m != nil {
		return m.Type
	}
	return ModelControlRequest_UNLOAD
}

//@@
//@@.. cpp:var:: message ModelControlResponse
//@@
//@@   Response message for ModelControl gRPC endpoint.
//@@
type ModelControlResponse struct {
	//@@
	//@@  .. cpp:var:: RequestStatus request_status
	//@@
	//@@     The status of the request, indicating success or failure.
	//@@
	RequestStatus        *RequestStatus `protobuf:"bytes,1,opt,name=request_status,json=requestStatus,proto3" json:"request_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ModelControlResponse) Reset()         { *m = ModelControlResponse{} }
func (m *ModelControlResponse) String() string { return proto.CompactTextString(m) }
func (*ModelControlResponse) ProtoMessage()    {}
func (*ModelControlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{5}
}

func (m *ModelControlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelControlResponse.Unmarshal(m, b)
}
func (m *ModelControlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelControlResponse.Marshal(b, m, deterministic)
}
func (m *ModelControlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelControlResponse.Merge(m, src)
}
func (m *ModelControlResponse) XXX_Size() int {
	return xxx_messageInfo_ModelControlResponse.Size(m)
}
func (m *ModelControlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelControlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModelControlResponse proto.InternalMessageInfo

func (m *ModelControlResponse) GetRequestStatus() *RequestStatus {
	if m != nil {
		return m.RequestStatus
	}
	return nil
}

//@@
//@@.. cpp:var:: message SharedMemoryControlRequest
//@@
//@@   Request message for managing registered shared memory regions in TRTIS.
//@@
type SharedMemoryControlRequest struct {
	//@@  .. cpp:var:: oneof shared_memory_control
	//@@
	//@@     Types of control operations for shared memory
	//@@
	//
	// Types that are valid to be assigned to SharedMemoryControl:
	//	*SharedMemoryControlRequest_Register_
	//	*SharedMemoryControlRequest_Unregister_
	//	*SharedMemoryControlRequest_UnregisterAll_
	//	*SharedMemoryControlRequest_Status_
	SharedMemoryControl  isSharedMemoryControlRequest_SharedMemoryControl `protobuf_oneof:"shared_memory_control"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *SharedMemoryControlRequest) Reset()         { *m = SharedMemoryControlRequest{} }
func (m *SharedMemoryControlRequest) String() string { return proto.CompactTextString(m) }
func (*SharedMemoryControlRequest) ProtoMessage()    {}
func (*SharedMemoryControlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{6}
}

func (m *SharedMemoryControlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryControlRequest.Unmarshal(m, b)
}
func (m *SharedMemoryControlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryControlRequest.Marshal(b, m, deterministic)
}
func (m *SharedMemoryControlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryControlRequest.Merge(m, src)
}
func (m *SharedMemoryControlRequest) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryControlRequest.Size(m)
}
func (m *SharedMemoryControlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryControlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryControlRequest proto.InternalMessageInfo

type isSharedMemoryControlRequest_SharedMemoryControl interface {
	isSharedMemoryControlRequest_SharedMemoryControl()
}

type SharedMemoryControlRequest_Register_ struct {
	Register *SharedMemoryControlRequest_Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type SharedMemoryControlRequest_Unregister_ struct {
	Unregister *SharedMemoryControlRequest_Unregister `protobuf:"bytes,2,opt,name=unregister,proto3,oneof"`
}

type SharedMemoryControlRequest_UnregisterAll_ struct {
	UnregisterAll *SharedMemoryControlRequest_UnregisterAll `protobuf:"bytes,3,opt,name=unregister_all,json=unregisterAll,proto3,oneof"`
}

type SharedMemoryControlRequest_Status_ struct {
	Status *SharedMemoryControlRequest_Status `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

func (*SharedMemoryControlRequest_Register_) isSharedMemoryControlRequest_SharedMemoryControl() {}

func (*SharedMemoryControlRequest_Unregister_) isSharedMemoryControlRequest_SharedMemoryControl() {}

func (*SharedMemoryControlRequest_UnregisterAll_) isSharedMemoryControlRequest_SharedMemoryControl() {}

func (*SharedMemoryControlRequest_Status_) isSharedMemoryControlRequest_SharedMemoryControl() {}

func (m *SharedMemoryControlRequest) GetSharedMemoryControl() isSharedMemoryControlRequest_SharedMemoryControl {
	if m != nil {
		return m.SharedMemoryControl
	}
	return nil
}

func (m *SharedMemoryControlRequest) GetRegister() *SharedMemoryControlRequest_Register {
	if x, ok := m.GetSharedMemoryControl().(*SharedMemoryControlRequest_Register_); ok {
		return x.Register
	}
	return nil
}

func (m *SharedMemoryControlRequest) GetUnregister() *SharedMemoryControlRequest_Unregister {
	if x, ok := m.GetSharedMemoryControl().(*SharedMemoryControlRequest_Unregister_); ok {
		return x.Unregister
	}
	return nil
}

func (m *SharedMemoryControlRequest) GetUnregisterAll() *SharedMemoryControlRequest_UnregisterAll {
	if x, ok := m.GetSharedMemoryControl().(*SharedMemoryControlRequest_UnregisterAll_); ok {
		return x.UnregisterAll
	}
	return nil
}

func (m *SharedMemoryControlRequest) GetStatus() *SharedMemoryControlRequest_Status {
	if x, ok := m.GetSharedMemoryControl().(*SharedMemoryControlRequest_Status_); ok {
		return x.Status
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SharedMemoryControlRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SharedMemoryControlRequest_Register_)(nil),
		(*SharedMemoryControlRequest_Unregister_)(nil),
		(*SharedMemoryControlRequest_UnregisterAll_)(nil),
		(*SharedMemoryControlRequest_Status_)(nil),
	}
}

//@@  .. cpp:var:: message Register
//@@
//@@     Register a shared memory region.
//@@
type SharedMemoryControlRequest_Register struct {
	//@@
	//@@  .. cpp:var:: string name
	//@@
	//@@     The name for this shared memory region.
	//@@
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//@@  .. cpp:var:: oneof shared_memory_types
	//@@
	//@@     Types of shared memory identifiers
	//@@
	//
	// Types that are valid to be assigned to SharedMemoryTypes:
	//	*SharedMemoryControlRequest_Register_SystemSharedMemory
	//	*SharedMemoryControlRequest_Register_CudaSharedMemory
	SharedMemoryTypes isSharedMemoryControlRequest_Register_SharedMemoryTypes `protobuf_oneof:"shared_memory_types"`
	//@@  .. cpp:var:: uint64 byte_size
	//@@
	//@@     Size of the shared memory block, in bytes.
	//@@
	ByteSize             uint64   `protobuf:"varint,4,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedMemoryControlRequest_Register) Reset()         { *m = SharedMemoryControlRequest_Register{} }
func (m *SharedMemoryControlRequest_Register) String() string { return proto.CompactTextString(m) }
func (*SharedMemoryControlRequest_Register) ProtoMessage()    {}
func (*SharedMemoryControlRequest_Register) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{6, 0}
}

func (m *SharedMemoryControlRequest_Register) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryControlRequest_Register.Unmarshal(m, b)
}
func (m *SharedMemoryControlRequest_Register) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryControlRequest_Register.Marshal(b, m, deterministic)
}
func (m *SharedMemoryControlRequest_Register) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryControlRequest_Register.Merge(m, src)
}
func (m *SharedMemoryControlRequest_Register) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryControlRequest_Register.Size(m)
}
func (m *SharedMemoryControlRequest_Register) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryControlRequest_Register.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryControlRequest_Register proto.InternalMessageInfo

func (m *SharedMemoryControlRequest_Register) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isSharedMemoryControlRequest_Register_SharedMemoryTypes interface {
	isSharedMemoryControlRequest_Register_SharedMemoryTypes()
}

type SharedMemoryControlRequest_Register_SystemSharedMemory struct {
	SystemSharedMemory *SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier `protobuf:"bytes,2,opt,name=system_shared_memory,json=systemSharedMemory,proto3,oneof"`
}

type SharedMemoryControlRequest_Register_CudaSharedMemory struct {
	CudaSharedMemory *SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier `protobuf:"bytes,3,opt,name=cuda_shared_memory,json=cudaSharedMemory,proto3,oneof"`
}

func (*SharedMemoryControlRequest_Register_SystemSharedMemory) isSharedMemoryControlRequest_Register_SharedMemoryTypes() {
}

func (*SharedMemoryControlRequest_Register_CudaSharedMemory) isSharedMemoryControlRequest_Register_SharedMemoryTypes() {
}

func (m *SharedMemoryControlRequest_Register) GetSharedMemoryTypes() isSharedMemoryControlRequest_Register_SharedMemoryTypes {
	if m != nil {
		return m.SharedMemoryTypes
	}
	return nil
}

func (m *SharedMemoryControlRequest_Register) GetSystemSharedMemory() *SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier {
	if x, ok := m.GetSharedMemoryTypes().(*SharedMemoryControlRequest_Register_SystemSharedMemory); ok {
		return x.SystemSharedMemory
	}
	return nil
}

func (m *SharedMemoryControlRequest_Register) GetCudaSharedMemory() *SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier {
	if x, ok := m.GetSharedMemoryTypes().(*SharedMemoryControlRequest_Register_CudaSharedMemory); ok {
		return x.CudaSharedMemory
	}
	return nil
}

func (m *SharedMemoryControlRequest_Register) GetByteSize() uint64 {
	if m != nil {
		return m.ByteSize
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SharedMemoryControlRequest_Register) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SharedMemoryControlRequest_Register_SystemSharedMemory)(nil),
		(*SharedMemoryControlRequest_Register_CudaSharedMemory)(nil),
	}
}

//@@
//@@  .. cpp:var:: message SystemSharedMemoryIdentifier
//@@
//@@     The identifier for this system shared memory region.
//@@
type SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier struct {
	//@@  .. cpp:var:: string shared_memory_key
	//@@
	//@@     The name of the shared memory region that holds the input data
	//@@     (or where the output data should be written).
	//@@
	SharedMemoryKey string `protobuf:"bytes,1,opt,name=shared_memory_key,json=sharedMemoryKey,proto3" json:"shared_memory_key,omitempty"`
	//@@  .. cpp:var:: uint64 offset
	//@@
	//@@     This is the offset of the shared memory block from the start
	//@@     of the shared memory region.
	//@@     start = offset, end = offset + byte_size;
	//@@
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier) Reset() {
	*m = SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier{}
}
func (m *SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier) String() string {
	return proto.CompactTextString(m)
}
func (*SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier) ProtoMessage() {}
func (*SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{6, 0, 0}
}

func (m *SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier.Unmarshal(m, b)
}
func (m *SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier.Marshal(b, m, deterministic)
}
func (m *SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier.Merge(m, src)
}
func (m *SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier.Size(m)
}
func (m *SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier proto.InternalMessageInfo

func (m *SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier) GetSharedMemoryKey() string {
	if m != nil {
		return m.SharedMemoryKey
	}
	return ""
}

func (m *SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

//@@
//@@  .. cpp:var:: message CUDASharedMemoryIdentifier
//@@
//@@     The identifier for this system shared memory region.
//@@
type SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier struct {
	//@@  .. cpp:var:: bytes raw_handle
	//@@
	//@@     The raw serialized cudaIPC handle.
	//@@
	RawHandle []byte `protobuf:"bytes,1,opt,name=raw_handle,json=rawHandle,proto3" json:"raw_handle,omitempty"`
	//@@  .. cpp:var:: int64 device_id
	//@@
	//@@     The GPU device ID on which the cudaIPC handle was created.
	//@@
	DeviceId             int64    `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier) Reset() {
	*m = SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier{}
}
func (m *SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier) String() string {
	return proto.CompactTextString(m)
}
func (*SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier) ProtoMessage() {}
func (*SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{6, 0, 1}
}

func (m *SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier.Unmarshal(m, b)
}
func (m *SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier.Marshal(b, m, deterministic)
}
func (m *SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier.Merge(m, src)
}
func (m *SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier.Size(m)
}
func (m *SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier proto.InternalMessageInfo

func (m *SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier) GetRawHandle() []byte {
	if m != nil {
		return m.RawHandle
	}
	return nil
}

func (m *SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

//@@  .. cpp:var:: message Unregister
//@@
//@@     Unregister a specified shared memory region.
//@@
type SharedMemoryControlRequest_Unregister struct {
	//@@
	//@@  .. cpp:var:: string name
	//@@
	//@@     The name for this shared memory region to unregister.
	//@@
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedMemoryControlRequest_Unregister) Reset()         { *m = SharedMemoryControlRequest_Unregister{} }
func (m *SharedMemoryControlRequest_Unregister) String() string { return proto.CompactTextString(m) }
func (*SharedMemoryControlRequest_Unregister) ProtoMessage()    {}
func (*SharedMemoryControlRequest_Unregister) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{6, 1}
}

func (m *SharedMemoryControlRequest_Unregister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryControlRequest_Unregister.Unmarshal(m, b)
}
func (m *SharedMemoryControlRequest_Unregister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryControlRequest_Unregister.Marshal(b, m, deterministic)
}
func (m *SharedMemoryControlRequest_Unregister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryControlRequest_Unregister.Merge(m, src)
}
func (m *SharedMemoryControlRequest_Unregister) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryControlRequest_Unregister.Size(m)
}
func (m *SharedMemoryControlRequest_Unregister) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryControlRequest_Unregister.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryControlRequest_Unregister proto.InternalMessageInfo

func (m *SharedMemoryControlRequest_Unregister) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//@@  .. cpp:var:: message UnregisterAll
//@@
//@@     Unregister all shared memory regions.
//@@
type SharedMemoryControlRequest_UnregisterAll struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedMemoryControlRequest_UnregisterAll) Reset() {
	*m = SharedMemoryControlRequest_UnregisterAll{}
}
func (m *SharedMemoryControlRequest_UnregisterAll) String() string { return proto.CompactTextString(m) }
func (*SharedMemoryControlRequest_UnregisterAll) ProtoMessage()    {}
func (*SharedMemoryControlRequest_UnregisterAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{6, 2}
}

func (m *SharedMemoryControlRequest_UnregisterAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryControlRequest_UnregisterAll.Unmarshal(m, b)
}
func (m *SharedMemoryControlRequest_UnregisterAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryControlRequest_UnregisterAll.Marshal(b, m, deterministic)
}
func (m *SharedMemoryControlRequest_UnregisterAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryControlRequest_UnregisterAll.Merge(m, src)
}
func (m *SharedMemoryControlRequest_UnregisterAll) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryControlRequest_UnregisterAll.Size(m)
}
func (m *SharedMemoryControlRequest_UnregisterAll) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryControlRequest_UnregisterAll.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryControlRequest_UnregisterAll proto.InternalMessageInfo

//@@  .. cpp:var:: message GetStatus
//@@
//@@     Get the status of all active shared memory regions.
//@@
type SharedMemoryControlRequest_Status struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedMemoryControlRequest_Status) Reset()         { *m = SharedMemoryControlRequest_Status{} }
func (m *SharedMemoryControlRequest_Status) String() string { return proto.CompactTextString(m) }
func (*SharedMemoryControlRequest_Status) ProtoMessage()    {}
func (*SharedMemoryControlRequest_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{6, 3}
}

func (m *SharedMemoryControlRequest_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryControlRequest_Status.Unmarshal(m, b)
}
func (m *SharedMemoryControlRequest_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryControlRequest_Status.Marshal(b, m, deterministic)
}
func (m *SharedMemoryControlRequest_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryControlRequest_Status.Merge(m, src)
}
func (m *SharedMemoryControlRequest_Status) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryControlRequest_Status.Size(m)
}
func (m *SharedMemoryControlRequest_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryControlRequest_Status.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryControlRequest_Status proto.InternalMessageInfo

//@@
//@@.. cpp:var:: message SharedMemoryControlResponse
//@@
//@@   Response message for SharedMemoryControl gRPC endpoint.
//@@
type SharedMemoryControlResponse struct {
	//@@
	//@@  .. cpp:var:: RequestStatus request_status
	//@@
	//@@     The status of the request, indicating success or failure.
	//@@
	RequestStatus *RequestStatus `protobuf:"bytes,1,opt,name=request_status,json=requestStatus,proto3" json:"request_status,omitempty"`
	// Types that are valid to be assigned to SharedMemoryControl:
	//	*SharedMemoryControlResponse_SharedMemoryStatus
	SharedMemoryControl  isSharedMemoryControlResponse_SharedMemoryControl `protobuf_oneof:"shared_memory_control"`
	XXX_NoUnkeyedLiteral struct{}                                          `json:"-"`
	XXX_unrecognized     []byte                                            `json:"-"`
	XXX_sizecache        int32                                             `json:"-"`
}

func (m *SharedMemoryControlResponse) Reset()         { *m = SharedMemoryControlResponse{} }
func (m *SharedMemoryControlResponse) String() string { return proto.CompactTextString(m) }
func (*SharedMemoryControlResponse) ProtoMessage()    {}
func (*SharedMemoryControlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{7}
}

func (m *SharedMemoryControlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryControlResponse.Unmarshal(m, b)
}
func (m *SharedMemoryControlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryControlResponse.Marshal(b, m, deterministic)
}
func (m *SharedMemoryControlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryControlResponse.Merge(m, src)
}
func (m *SharedMemoryControlResponse) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryControlResponse.Size(m)
}
func (m *SharedMemoryControlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryControlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryControlResponse proto.InternalMessageInfo

func (m *SharedMemoryControlResponse) GetRequestStatus() *RequestStatus {
	if m != nil {
		return m.RequestStatus
	}
	return nil
}

type isSharedMemoryControlResponse_SharedMemoryControl interface {
	isSharedMemoryControlResponse_SharedMemoryControl()
}

type SharedMemoryControlResponse_SharedMemoryStatus struct {
	SharedMemoryStatus *SharedMemoryControlResponse_Status `protobuf:"bytes,2,opt,name=shared_memory_status,json=sharedMemoryStatus,proto3,oneof"`
}

func (*SharedMemoryControlResponse_SharedMemoryStatus) isSharedMemoryControlResponse_SharedMemoryControl() {
}

func (m *SharedMemoryControlResponse) GetSharedMemoryControl() isSharedMemoryControlResponse_SharedMemoryControl {
	if m != nil {
		return m.SharedMemoryControl
	}
	return nil
}

func (m *SharedMemoryControlResponse) GetSharedMemoryStatus() *SharedMemoryControlResponse_Status {
	if x, ok := m.GetSharedMemoryControl().(*SharedMemoryControlResponse_SharedMemoryStatus); ok {
		return x.SharedMemoryStatus
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SharedMemoryControlResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SharedMemoryControlResponse_SharedMemoryStatus)(nil),
	}
}

//@@
//@@.. cpp:var:: message Status
//@@
//@@   Status of all active shared memory regions.
//@@
type SharedMemoryControlResponse_Status struct {
	//@@
	//@@  .. cpp:var:: SharedMemoryRegion shared_memory_region
	//@@
	//@@     The list of active/registered shared memory regions.
	//@@
	SharedMemoryRegion   []*SharedMemoryRegion `protobuf:"bytes,1,rep,name=shared_memory_region,json=sharedMemoryRegion,proto3" json:"shared_memory_region,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SharedMemoryControlResponse_Status) Reset()         { *m = SharedMemoryControlResponse_Status{} }
func (m *SharedMemoryControlResponse_Status) String() string { return proto.CompactTextString(m) }
func (*SharedMemoryControlResponse_Status) ProtoMessage()    {}
func (*SharedMemoryControlResponse_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{7, 0}
}

func (m *SharedMemoryControlResponse_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryControlResponse_Status.Unmarshal(m, b)
}
func (m *SharedMemoryControlResponse_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryControlResponse_Status.Marshal(b, m, deterministic)
}
func (m *SharedMemoryControlResponse_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryControlResponse_Status.Merge(m, src)
}
func (m *SharedMemoryControlResponse_Status) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryControlResponse_Status.Size(m)
}
func (m *SharedMemoryControlResponse_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryControlResponse_Status.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryControlResponse_Status proto.InternalMessageInfo

func (m *SharedMemoryControlResponse_Status) GetSharedMemoryRegion() []*SharedMemoryRegion {
	if m != nil {
		return m.SharedMemoryRegion
	}
	return nil
}

//@@
//@@.. cpp:var:: message InferRequest
//@@
//@@   Request message for Infer gRPC endpoint.
//@@
type InferRequest struct {
	//@@  .. cpp:var:: string model_name
	//@@
	//@@     The name of the model to use for inferencing.
	//@@
	ModelName string `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	//@@  .. cpp:var:: int64 version
	//@@
	//@@     The version of the model to use for inference. If -1
	//@@     the latest/most-recent version of the model is used.
	//@@
	ModelVersion int64 `protobuf:"varint,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	//@@  .. cpp:var:: InferRequestHeader meta_data
	//@@
	//@@     Meta-data for the request: input tensors, output
	//@@     tensors, etc.
	//@@
	MetaData *InferRequestHeader `protobuf:"bytes,3,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	//@@  .. cpp:var:: bytes raw_input (repeated)
	//@@
	//@@     The raw input tensor data in the order specified in 'meta_data'.
	//@@
	RawInput             [][]byte `protobuf:"bytes,4,rep,name=raw_input,json=rawInput,proto3" json:"raw_input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InferRequest) Reset()         { *m = InferRequest{} }
func (m *InferRequest) String() string { return proto.CompactTextString(m) }
func (*InferRequest) ProtoMessage()    {}
func (*InferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{8}
}

func (m *InferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InferRequest.Unmarshal(m, b)
}
func (m *InferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InferRequest.Marshal(b, m, deterministic)
}
func (m *InferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InferRequest.Merge(m, src)
}
func (m *InferRequest) XXX_Size() int {
	return xxx_messageInfo_InferRequest.Size(m)
}
func (m *InferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InferRequest proto.InternalMessageInfo

func (m *InferRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *InferRequest) GetModelVersion() int64 {
	if m != nil {
		return m.ModelVersion
	}
	return 0
}

func (m *InferRequest) GetMetaData() *InferRequestHeader {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *InferRequest) GetRawInput() [][]byte {
	if m != nil {
		return m.RawInput
	}
	return nil
}

//@@
//@@.. cpp:var:: message InferResponse
//@@
//@@   Response message for Infer gRPC endpoint.
//@@
type InferResponse struct {
	//@@
	//@@  .. cpp:var:: RequestStatus request_status
	//@@
	//@@     The status of the request, indicating success or failure.
	//@@
	RequestStatus *RequestStatus `protobuf:"bytes,1,opt,name=request_status,json=requestStatus,proto3" json:"request_status,omitempty"`
	//@@  .. cpp:var:: InferResponseHeader meta_data
	//@@
	//@@     The response meta-data for the output tensors.
	//@@
	MetaData *InferResponseHeader `protobuf:"bytes,2,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	//@@  .. cpp:var:: bytes raw_output (repeated)
	//@@
	//@@     The raw output tensor data in the order specified in 'meta_data'.
	//@@
	RawOutput            [][]byte `protobuf:"bytes,3,rep,name=raw_output,json=rawOutput,proto3" json:"raw_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InferResponse) Reset()         { *m = InferResponse{} }
func (m *InferResponse) String() string { return proto.CompactTextString(m) }
func (*InferResponse) ProtoMessage()    {}
func (*InferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{9}
}

func (m *InferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InferResponse.Unmarshal(m, b)
}
func (m *InferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InferResponse.Marshal(b, m, deterministic)
}
func (m *InferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InferResponse.Merge(m, src)
}
func (m *InferResponse) XXX_Size() int {
	return xxx_messageInfo_InferResponse.Size(m)
}
func (m *InferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InferResponse proto.InternalMessageInfo

func (m *InferResponse) GetRequestStatus() *RequestStatus {
	if m != nil {
		return m.RequestStatus
	}
	return nil
}

func (m *InferResponse) GetMetaData() *InferResponseHeader {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *InferResponse) GetRawOutput() [][]byte {
	if m != nil {
		return m.RawOutput
	}
	return nil
}

//@@
//@@.. cpp:var:: message RepositoryRequest
//@@
//@@   Request message for Repository gRPC endpoint.
//@@
type RepositoryRequest struct {
	//@@  .. cpp:var:: oneof request_type
	//@@
	//@@     Types of the repository request
	//@@
	//
	// Types that are valid to be assigned to RequestType:
	//	*RepositoryRequest_Index
	RequestType          isRepositoryRequest_RequestType `protobuf_oneof:"request_type"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *RepositoryRequest) Reset()         { *m = RepositoryRequest{} }
func (m *RepositoryRequest) String() string { return proto.CompactTextString(m) }
func (*RepositoryRequest) ProtoMessage()    {}
func (*RepositoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{10}
}

func (m *RepositoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryRequest.Unmarshal(m, b)
}
func (m *RepositoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryRequest.Marshal(b, m, deterministic)
}
func (m *RepositoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryRequest.Merge(m, src)
}
func (m *RepositoryRequest) XXX_Size() int {
	return xxx_messageInfo_RepositoryRequest.Size(m)
}
func (m *RepositoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryRequest proto.InternalMessageInfo

type isRepositoryRequest_RequestType interface {
	isRepositoryRequest_RequestType()
}

type RepositoryRequest_Index struct {
	Index bool `protobuf:"varint,1,opt,name=index,proto3,oneof"`
}

func (*RepositoryRequest_Index) isRepositoryRequest_RequestType() {}

func (m *RepositoryRequest) GetRequestType() isRepositoryRequest_RequestType {
	if m != nil {
		return m.RequestType
	}
	return nil
}

func (m *RepositoryRequest) GetIndex() bool {
	if x, ok := m.GetRequestType().(*RepositoryRequest_Index); ok {
		return x.Index
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RepositoryRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RepositoryRequest_Index)(nil),
	}
}

//@@
//@@.. cpp:var:: message RepositoryResponse
//@@
//@@   Response message for Repository gRPC endpoint.
//@@
type RepositoryResponse struct {
	//@@
	//@@  .. cpp:var:: RequestStatus request_status
	//@@
	//@@     The status of the request, indicating success or failure.
	//@@
	RequestStatus *RequestStatus `protobuf:"bytes,1,opt,name=request_status,json=requestStatus,proto3" json:"request_status,omitempty"`
	//@@  .. cpp:var:: oneof response_type
	//@@
	//@@     Types of the repository reponse, which is one-to-one mapping to
	//@@     the repository request type.
	//@@
	//
	// Types that are valid to be assigned to ResponseType:
	//	*RepositoryResponse_Index
	ResponseType         isRepositoryResponse_ResponseType `protobuf_oneof:"response_type"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *RepositoryResponse) Reset()         { *m = RepositoryResponse{} }
func (m *RepositoryResponse) String() string { return proto.CompactTextString(m) }
func (*RepositoryResponse) ProtoMessage()    {}
func (*RepositoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_626e658682f5c341, []int{11}
}

func (m *RepositoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryResponse.Unmarshal(m, b)
}
func (m *RepositoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryResponse.Marshal(b, m, deterministic)
}
func (m *RepositoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryResponse.Merge(m, src)
}
func (m *RepositoryResponse) XXX_Size() int {
	return xxx_messageInfo_RepositoryResponse.Size(m)
}
func (m *RepositoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryResponse proto.InternalMessageInfo

func (m *RepositoryResponse) GetRequestStatus() *RequestStatus {
	if m != nil {
		return m.RequestStatus
	}
	return nil
}

type isRepositoryResponse_ResponseType interface {
	isRepositoryResponse_ResponseType()
}

type RepositoryResponse_Index struct {
	Index *ModelRepositoryIndex `protobuf:"bytes,2,opt,name=index,proto3,oneof"`
}

func (*RepositoryResponse_Index) isRepositoryResponse_ResponseType() {}

func (m *RepositoryResponse) GetResponseType() isRepositoryResponse_ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return nil
}

func (m *RepositoryResponse) GetIndex() *ModelRepositoryIndex {
	if x, ok := m.GetResponseType().(*RepositoryResponse_Index); ok {
		return x.Index
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RepositoryResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RepositoryResponse_Index)(nil),
	}
}

func init() {
	proto.RegisterEnum("nvidia.inferenceserver.ModelControlRequest_Type", ModelControlRequest_Type_name, ModelControlRequest_Type_value)
	proto.RegisterType((*StatusRequest)(nil), "nvidia.inferenceserver.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "nvidia.inferenceserver.StatusResponse")
	proto.RegisterType((*HealthRequest)(nil), "nvidia.inferenceserver.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "nvidia.inferenceserver.HealthResponse")
	proto.RegisterType((*ModelControlRequest)(nil), "nvidia.inferenceserver.ModelControlRequest")
	proto.RegisterType((*ModelControlResponse)(nil), "nvidia.inferenceserver.ModelControlResponse")
	proto.RegisterType((*SharedMemoryControlRequest)(nil), "nvidia.inferenceserver.SharedMemoryControlRequest")
	proto.RegisterType((*SharedMemoryControlRequest_Register)(nil), "nvidia.inferenceserver.SharedMemoryControlRequest.Register")
	proto.RegisterType((*SharedMemoryControlRequest_Register_SystemSharedMemoryIdentifier)(nil), "nvidia.inferenceserver.SharedMemoryControlRequest.Register.SystemSharedMemoryIdentifier")
	proto.RegisterType((*SharedMemoryControlRequest_Register_CUDASharedMemoryIdentifier)(nil), "nvidia.inferenceserver.SharedMemoryControlRequest.Register.CUDASharedMemoryIdentifier")
	proto.RegisterType((*SharedMemoryControlRequest_Unregister)(nil), "nvidia.inferenceserver.SharedMemoryControlRequest.Unregister")
	proto.RegisterType((*SharedMemoryControlRequest_UnregisterAll)(nil), "nvidia.inferenceserver.SharedMemoryControlRequest.UnregisterAll")
	proto.RegisterType((*SharedMemoryControlRequest_Status)(nil), "nvidia.inferenceserver.SharedMemoryControlRequest.Status")
	proto.RegisterType((*SharedMemoryControlResponse)(nil), "nvidia.inferenceserver.SharedMemoryControlResponse")
	proto.RegisterType((*SharedMemoryControlResponse_Status)(nil), "nvidia.inferenceserver.SharedMemoryControlResponse.Status")
	proto.RegisterType((*InferRequest)(nil), "nvidia.inferenceserver.InferRequest")
	proto.RegisterType((*InferResponse)(nil), "nvidia.inferenceserver.InferResponse")
	proto.RegisterType((*RepositoryRequest)(nil), "nvidia.inferenceserver.RepositoryRequest")
	proto.RegisterType((*RepositoryResponse)(nil), "nvidia.inferenceserver.RepositoryResponse")
}

func init() { proto.RegisterFile("grpc_service.proto", fileDescriptor_626e658682f5c341) }

var fileDescriptor_626e658682f5c341 = []byte{
	// 1003 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x5d, 0x6e, 0xdb, 0x46,
	0x10, 0x26, 0x23, 0x45, 0xa0, 0xc6, 0x92, 0x9c, 0xac, 0x1d, 0x57, 0x60, 0x52, 0xc0, 0x60, 0x92,
	0xc2, 0x75, 0x02, 0x21, 0x50, 0x9e, 0xda, 0xa0, 0x40, 0x6d, 0x0b, 0x88, 0x84, 0xe6, 0xa7, 0x58,
	0xd5, 0x46, 0x02, 0x14, 0x60, 0xd7, 0xe2, 0x28, 0x26, 0x22, 0x91, 0xea, 0xee, 0xca, 0xae, 0xf2,
	0xd4, 0xa7, 0x3e, 0xf5, 0x00, 0xed, 0x0d, 0xda, 0x1b, 0xb4, 0x17, 0xe8, 0x09, 0xfa, 0xd8, 0xc3,
	0x14, 0xbb, 0x4b, 0x49, 0xa4, 0x23, 0x26, 0xb2, 0x0d, 0x3d, 0x59, 0x33, 0xdc, 0xf9, 0xe6, 0x9b,
	0x99, 0x6f, 0x7f, 0x0c, 0xe4, 0x0d, 0x1f, 0xf5, 0x7c, 0x81, 0xfc, 0x34, 0xec, 0x61, 0x63, 0xc4,
	0x63, 0x19, 0x93, 0xad, 0xe8, 0x34, 0x0c, 0x42, 0xd6, 0x08, 0xa3, 0x3e, 0x72, 0x8c, 0x7a, 0xa8,
	0x3e, 0x23, 0x77, 0xcb, 0x6c, 0x14, 0x9a, 0x25, 0xee, 0x26, 0xc7, 0x1f, 0xc7, 0x28, 0xa4, 0x2f,
	0x24, 0x93, 0x63, 0x91, 0x78, 0x37, 0xcc, 0xc2, 0x8c, 0xd3, 0x6b, 0x40, 0xb5, 0xab, 0x6d, 0x6a,
	0x42, 0xc8, 0xa7, 0x00, 0xc3, 0x38, 0xc0, 0x81, 0x1f, 0xb1, 0x21, 0xd6, 0xed, 0x6d, 0x7b, 0xa7,
	0x4c, 0xcb, 0xda, 0xf3, 0x82, 0x0d, 0xd1, 0xfb, 0xd3, 0x86, 0xda, 0x34, 0x40, 0x8c, 0xe2, 0x48,
	0x20, 0x79, 0x06, 0xb5, 0x6c, 0x3e, 0x1d, 0xb5, 0xd6, 0xbc, 0xdf, 0x58, 0xcc, 0xb4, 0x91, 0xa4,
	0x4a, 0x60, 0xaa, 0x3c, 0x6d, 0x92, 0x0e, 0x54, 0x33, 0x3c, 0xeb, 0xd7, 0x34, 0xd8, 0xbd, 0x3c,
	0xb0, 0xae, 0xfe, 0x93, 0x60, 0x55, 0x44, 0xca, 0xf2, 0xee, 0x42, 0xb5, 0x8d, 0x6c, 0x20, 0x4f,
	0xa6, 0xb5, 0x11, 0x28, 0xaa, 0x4a, 0x92, 0xaa, 0xf4, 0x6f, 0xef, 0x14, 0x6a, 0xd3, 0x45, 0x2b,
	0xa9, 0x67, 0x0b, 0x4a, 0x27, 0x1a, 0x5f, 0x17, 0xe2, 0xd0, 0xc4, 0xf2, 0x7e, 0xb3, 0x61, 0xe3,
	0xb9, 0x6a, 0xeb, 0x41, 0x1c, 0x49, 0x1e, 0x0f, 0x96, 0xeb, 0x3f, 0x69, 0x41, 0x51, 0x4e, 0x46,
	0xa8, 0xc1, 0x6a, 0xcd, 0x47, 0x79, 0x94, 0x16, 0x20, 0x37, 0xbe, 0x9b, 0x8c, 0x90, 0xea, 0x68,
	0xef, 0x0e, 0x14, 0x95, 0x45, 0x00, 0x4a, 0x87, 0x2f, 0x9e, 0xbd, 0xdc, 0x6b, 0xdd, 0xb0, 0x88,
	0x03, 0x45, 0xfd, 0xcb, 0xf6, 0x02, 0xd8, 0xcc, 0xc6, 0xaf, 0xa2, 0x31, 0xde, 0xef, 0x0e, 0xb8,
	0xdd, 0x13, 0xc6, 0x31, 0x78, 0x8e, 0xc3, 0x98, 0x4f, 0xce, 0xf5, 0xe1, 0x35, 0x38, 0x1c, 0xdf,
	0x84, 0x42, 0x22, 0x4f, 0xd2, 0x3c, 0xc9, 0x95, 0x40, 0x2e, 0x4a, 0x83, 0x26, 0x10, 0x6d, 0x8b,
	0xce, 0xe0, 0x88, 0x0f, 0x30, 0x8e, 0x66, 0xe0, 0x46, 0x5f, 0x5f, 0x5d, 0x02, 0xfc, 0x70, 0x06,
	0xd2, 0xb6, 0x68, 0x0a, 0x92, 0x84, 0x50, 0x9b, 0x5b, 0x3e, 0x1b, 0x0c, 0xea, 0x05, 0x9d, 0xe4,
	0xeb, 0x2b, 0x25, 0xd9, 0x1b, 0x0c, 0xda, 0x16, 0xad, 0x8e, 0xd3, 0x0e, 0xd2, 0x85, 0x52, 0x32,
	0x8b, 0xa2, 0x4e, 0xf1, 0xc5, 0x25, 0x52, 0x98, 0x81, 0xb4, 0x2d, 0x9a, 0x40, 0xb9, 0x7f, 0x14,
	0xc1, 0x99, 0x76, 0x4e, 0x6d, 0x9a, 0x94, 0x14, 0xf5, 0x6f, 0xf2, 0xab, 0x0d, 0x9b, 0x62, 0x22,
	0x24, 0x0e, 0x7d, 0xa1, 0x71, 0xfd, 0xa1, 0x06, 0x4e, 0x9a, 0xf9, 0xea, 0x0a, 0x93, 0x6a, 0x74,
	0x35, 0x6e, 0x7a, 0x65, 0x27, 0xc0, 0x48, 0x86, 0xfd, 0x50, 0xf7, 0x99, 0x88, 0xf7, 0xbe, 0x93,
	0x5f, 0x6c, 0x20, 0xbd, 0x71, 0xc0, 0xce, 0x91, 0x31, 0x4d, 0x3f, 0xba, 0x0a, 0x99, 0x83, 0xc3,
	0xd6, 0x5e, 0x2e, 0x95, 0x1b, 0x2a, 0x67, 0x86, 0xc8, 0x6d, 0x28, 0x1f, 0x4f, 0x24, 0xfa, 0x22,
	0x7c, 0x87, 0x7a, 0x20, 0x45, 0xea, 0x28, 0x47, 0x37, 0x7c, 0x87, 0xee, 0x31, 0xdc, 0xf9, 0x50,
	0x6d, 0x64, 0x17, 0x6e, 0x66, 0xf8, 0xfb, 0x6f, 0x71, 0x92, 0x74, 0x7d, 0x5d, 0xa4, 0x42, 0xbe,
	0xc1, 0x89, 0x3a, 0x55, 0xe2, 0x7e, 0x5f, 0xa0, 0xd4, 0x1d, 0x2f, 0xd2, 0xc4, 0x72, 0x5f, 0x81,
	0x9b, 0x4f, 0x59, 0x9d, 0x2d, 0x9c, 0x9d, 0xf9, 0x27, 0x2c, 0x0a, 0x06, 0x66, 0xa0, 0x15, 0x5a,
	0xe6, 0xec, 0xac, 0xad, 0x1d, 0x8a, 0x7d, 0x80, 0xea, 0xa6, 0xf1, 0xc3, 0x40, 0xe3, 0x16, 0xa8,
	0x63, 0x1c, 0x9d, 0x60, 0xff, 0x16, 0x6c, 0x64, 0xd9, 0xa9, 0x83, 0x44, 0xb8, 0xdb, 0x00, 0x73,
	0x85, 0x2e, 0xd2, 0x8a, 0xbb, 0x0e, 0xd5, 0x8c, 0x86, 0x5d, 0x07, 0x4a, 0x46, 0x71, 0xfb, 0x9f,
	0xc0, 0xad, 0x2c, 0x66, 0xcf, 0x8c, 0xc1, 0xfb, 0xef, 0x1a, 0xdc, 0x5e, 0x38, 0x9e, 0x95, 0x1c,
	0xd1, 0x11, 0x6c, 0x66, 0x69, 0x64, 0x6e, 0x9e, 0x2f, 0x2f, 0xa4, 0x1f, 0x43, 0x70, 0xbe, 0xa5,
	0x48, 0x7a, 0x72, 0xc6, 0xeb, 0xf6, 0xa7, 0x0d, 0x20, 0xdf, 0x9f, 0xcf, 0xac, 0xfa, 0x14, 0x47,
	0x75, 0x7b, 0xbb, 0xb0, 0xb3, 0xd6, 0xdc, 0x5d, 0x26, 0x33, 0xd5, 0x11, 0xd9, 0x3c, 0xc6, 0x97,
	0xdf, 0xde, 0xbf, 0x6c, 0xa8, 0x74, 0x14, 0xe6, 0x92, 0x97, 0xce, 0x5d, 0xa8, 0x9a, 0xcf, 0xa7,
	0xc8, 0x85, 0xe2, 0x67, 0xc4, 0x51, 0xd1, 0xce, 0x23, 0xe3, 0x23, 0x4f, 0xa1, 0x3c, 0x44, 0xc9,
	0xfc, 0x80, 0x49, 0x96, 0x6c, 0xbd, 0xdc, 0x02, 0xd2, 0xc9, 0xdb, 0xc8, 0x02, 0xe4, 0xd4, 0x51,
	0xc1, 0x2d, 0x26, 0x99, 0x92, 0xa1, 0x52, 0x69, 0x18, 0x8d, 0xc6, 0xb2, 0x5e, 0xdc, 0x2e, 0xec,
	0x54, 0xa8, 0xc3, 0xd9, 0x59, 0x47, 0xd9, 0xde, 0x3f, 0x36, 0x54, 0x93, 0xe8, 0x95, 0x68, 0xa1,
	0x9d, 0xae, 0xc2, 0x08, 0xe0, 0xc1, 0x47, 0xaa, 0x30, 0x3c, 0xde, 0x2b, 0x23, 0xd9, 0x6c, 0xf1,
	0x58, 0xaa, 0x3a, 0x0a, 0xba, 0x0e, 0x55, 0xd8, 0x4b, 0xed, 0xf0, 0x9e, 0xc0, 0x4d, 0x8a, 0xa3,
	0x58, 0x84, 0x52, 0x0f, 0xcc, 0xcc, 0x61, 0x0b, 0xae, 0x87, 0x51, 0x80, 0x3f, 0xe9, 0x12, 0x9c,
	0xb6, 0x45, 0x8d, 0xb9, 0x5f, 0x83, 0xca, 0xb4, 0x46, 0x7d, 0x7f, 0xff, 0x6d, 0x03, 0x49, 0x47,
	0xaf, 0xa4, 0x15, 0xad, 0x29, 0x19, 0xd3, 0x86, 0x87, 0x1f, 0x7c, 0x6b, 0xcc, 0xd9, 0x74, 0x54,
	0xcc, 0x9c, 0xfa, 0x3a, 0x54, 0x79, 0xc2, 0x4f, 0x73, 0x6f, 0xfe, 0x7b, 0x1d, 0xd6, 0x9e, 0xd2,
	0x6f, 0x0f, 0xba, 0xe6, 0x55, 0x4b, 0x5e, 0xcf, 0x76, 0x43, 0x2e, 0xcd, 0xcc, 0x0b, 0xd5, 0xfd,
	0xec, 0x63, 0xcb, 0x4c, 0x36, 0xcf, 0x52, 0xd0, 0xe6, 0x6d, 0x97, 0x0f, 0x9d, 0x79, 0x20, 0xe6,
	0x43, 0x67, 0x9f, 0x88, 0x9e, 0x45, 0x8e, 0xe0, 0xba, 0x1e, 0x3f, 0xb9, 0xb7, 0x8c, 0xc6, 0xdd,
	0xfb, 0x4b, 0x69, 0xc8, 0xb3, 0xc8, 0x0f, 0xb0, 0xd6, 0x95, 0x1c, 0xd9, 0x70, 0x15, 0xe8, 0x3b,
	0xf6, 0x23, 0x9b, 0xbc, 0x85, 0x4a, 0xfa, 0x75, 0x47, 0x1e, 0x5c, 0xe0, 0x0d, 0xe9, 0x3e, 0x5c,
	0x6e, 0xf1, 0xac, 0x9c, 0x9f, 0x6d, 0xd8, 0x58, 0x70, 0x4e, 0x92, 0xe6, 0xc5, 0x2f, 0x65, 0xf7,
	0xf1, 0x25, 0x0e, 0x62, 0xcf, 0x22, 0x08, 0x30, 0x17, 0x27, 0xf9, 0x3c, 0x7f, 0x2b, 0x9c, 0xdb,
	0x8c, 0xee, 0xee, 0x32, 0x4b, 0xa7, 0x69, 0x8e, 0x4b, 0xfa, 0xff, 0xa9, 0xc7, 0xff, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x9a, 0xc0, 0x82, 0x39, 0xb3, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GRPCServiceClient is the client API for GRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GRPCServiceClient interface {
	//@@  .. cpp:var:: rpc Status(StatusRequest) returns (StatusResponse)
	//@@
	//@@     Get status for entire inference server or for a specified model.
	//@@
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	//@@  .. cpp:var:: rpc Health(HealthRequest) returns (HealthResponse)
	//@@
	//@@     Check liveness and readiness of the inference server.
	//@@
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	//@@  .. cpp:var:: rpc Infer(InferRequest) returns (InferResponse)
	//@@
	//@@     Request inference using a specific model. [ To handle large input
	//@@     tensors likely need to set the maximum message size to that they
	//@@     can be transmitted in one pass.
	//@@
	Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (*InferResponse, error)
	//@@  .. cpp:var:: rpc StreamInfer(stream InferRequest) returns (stream
	//@@     InferResponse)
	//@@
	//@@     Request inferences using a specific model in a streaming manner.
	//@@     Individual inference requests sent through the same stream will be
	//@@     processed in order and be returned on completion
	//@@
	StreamInfer(ctx context.Context, opts ...grpc.CallOption) (GRPCService_StreamInferClient, error)
	//@@  .. cpp:var:: rpc ModelControl(ModelControlRequest) returns
	//@@     (ModelControlResponse)
	//@@
	//@@     Request to load / unload a specified model.
	//@@
	ModelControl(ctx context.Context, in *ModelControlRequest, opts ...grpc.CallOption) (*ModelControlResponse, error)
	//@@  .. cpp:var:: rpc SharedMemoryControl(SharedMemoryControlRequest) returns
	//@@     (SharedMemoryControlResponse)
	//@@
	//@@     Request to register / unregister a specified shared memory region.
	//@@
	SharedMemoryControl(ctx context.Context, in *SharedMemoryControlRequest, opts ...grpc.CallOption) (*SharedMemoryControlResponse, error)
	//@@  .. cpp:var:: rpc Status(RepositoryRequest) returns (RepositoryResponse)
	//@@
	//@@     Get status associated with the model repository.
	//@@
	Repository(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*RepositoryResponse, error)
}

type gRPCServiceClient struct {
	cc *grpc.ClientConn
}

func NewGRPCServiceClient(cc *grpc.ClientConn) GRPCServiceClient {
	return &gRPCServiceClient{cc}
}

func (c *gRPCServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/nvidia.inferenceserver.GRPCService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/nvidia.inferenceserver.GRPCService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCServiceClient) Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (*InferResponse, error) {
	out := new(InferResponse)
	err := c.cc.Invoke(ctx, "/nvidia.inferenceserver.GRPCService/Infer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCServiceClient) StreamInfer(ctx context.Context, opts ...grpc.CallOption) (GRPCService_StreamInferClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GRPCService_serviceDesc.Streams[0], "/nvidia.inferenceserver.GRPCService/StreamInfer", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCServiceStreamInferClient{stream}
	return x, nil
}

type GRPCService_StreamInferClient interface {
	Send(*InferRequest) error
	Recv() (*InferResponse, error)
	grpc.ClientStream
}

type gRPCServiceStreamInferClient struct {
	grpc.ClientStream
}

func (x *gRPCServiceStreamInferClient) Send(m *InferRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gRPCServiceStreamInferClient) Recv() (*InferResponse, error) {
	m := new(InferResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gRPCServiceClient) ModelControl(ctx context.Context, in *ModelControlRequest, opts ...grpc.CallOption) (*ModelControlResponse, error) {
	out := new(ModelControlResponse)
	err := c.cc.Invoke(ctx, "/nvidia.inferenceserver.GRPCService/ModelControl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCServiceClient) SharedMemoryControl(ctx context.Context, in *SharedMemoryControlRequest, opts ...grpc.CallOption) (*SharedMemoryControlResponse, error) {
	out := new(SharedMemoryControlResponse)
	err := c.cc.Invoke(ctx, "/nvidia.inferenceserver.GRPCService/SharedMemoryControl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCServiceClient) Repository(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*RepositoryResponse, error) {
	out := new(RepositoryResponse)
	err := c.cc.Invoke(ctx, "/nvidia.inferenceserver.GRPCService/Repository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCServiceServer is the server API for GRPCService service.
type GRPCServiceServer interface {
	//@@  .. cpp:var:: rpc Status(StatusRequest) returns (StatusResponse)
	//@@
	//@@     Get status for entire inference server or for a specified model.
	//@@
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	//@@  .. cpp:var:: rpc Health(HealthRequest) returns (HealthResponse)
	//@@
	//@@     Check liveness and readiness of the inference server.
	//@@
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	//@@  .. cpp:var:: rpc Infer(InferRequest) returns (InferResponse)
	//@@
	//@@     Request inference using a specific model. [ To handle large input
	//@@     tensors likely need to set the maximum message size to that they
	//@@     can be transmitted in one pass.
	//@@
	Infer(context.Context, *InferRequest) (*InferResponse, error)
	//@@  .. cpp:var:: rpc StreamInfer(stream InferRequest) returns (stream
	//@@     InferResponse)
	//@@
	//@@     Request inferences using a specific model in a streaming manner.
	//@@     Individual inference requests sent through the same stream will be
	//@@     processed in order and be returned on completion
	//@@
	StreamInfer(GRPCService_StreamInferServer) error
	//@@  .. cpp:var:: rpc ModelControl(ModelControlRequest) returns
	//@@     (ModelControlResponse)
	//@@
	//@@     Request to load / unload a specified model.
	//@@
	ModelControl(context.Context, *ModelControlRequest) (*ModelControlResponse, error)
	//@@  .. cpp:var:: rpc SharedMemoryControl(SharedMemoryControlRequest) returns
	//@@     (SharedMemoryControlResponse)
	//@@
	//@@     Request to register / unregister a specified shared memory region.
	//@@
	SharedMemoryControl(context.Context, *SharedMemoryControlRequest) (*SharedMemoryControlResponse, error)
	//@@  .. cpp:var:: rpc Status(RepositoryRequest) returns (RepositoryResponse)
	//@@
	//@@     Get status associated with the model repository.
	//@@
	Repository(context.Context, *RepositoryRequest) (*RepositoryResponse, error)
}

// UnimplementedGRPCServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGRPCServiceServer struct {
}

func (*UnimplementedGRPCServiceServer) Status(ctx context.Context, req *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedGRPCServiceServer) Health(ctx context.Context, req *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (*UnimplementedGRPCServiceServer) Infer(ctx context.Context, req *InferRequest) (*InferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Infer not implemented")
}
func (*UnimplementedGRPCServiceServer) StreamInfer(srv GRPCService_StreamInferServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamInfer not implemented")
}
func (*UnimplementedGRPCServiceServer) ModelControl(ctx context.Context, req *ModelControlRequest) (*ModelControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModelControl not implemented")
}
func (*UnimplementedGRPCServiceServer) SharedMemoryControl(ctx context.Context, req *SharedMemoryControlRequest) (*SharedMemoryControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SharedMemoryControl not implemented")
}
func (*UnimplementedGRPCServiceServer) Repository(ctx context.Context, req *RepositoryRequest) (*RepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Repository not implemented")
}

func RegisterGRPCServiceServer(s *grpc.Server, srv GRPCServiceServer) {
	s.RegisterService(&_GRPCService_serviceDesc, srv)
}

func _GRPCService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.inferenceserver.GRPCService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.inferenceserver.GRPCService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCService_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCServiceServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.inferenceserver.GRPCService/Infer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCServiceServer).Infer(ctx, req.(*InferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCService_StreamInfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GRPCServiceServer).StreamInfer(&gRPCServiceStreamInferServer{stream})
}

type GRPCService_StreamInferServer interface {
	Send(*InferResponse) error
	Recv() (*InferRequest, error)
	grpc.ServerStream
}

type gRPCServiceStreamInferServer struct {
	grpc.ServerStream
}

func (x *gRPCServiceStreamInferServer) Send(m *InferResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gRPCServiceStreamInferServer) Recv() (*InferRequest, error) {
	m := new(InferRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GRPCService_ModelControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCServiceServer).ModelControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.inferenceserver.GRPCService/ModelControl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCServiceServer).ModelControl(ctx, req.(*ModelControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCService_SharedMemoryControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SharedMemoryControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCServiceServer).SharedMemoryControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.inferenceserver.GRPCService/SharedMemoryControl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCServiceServer).SharedMemoryControl(ctx, req.(*SharedMemoryControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCService_Repository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCServiceServer).Repository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvidia.inferenceserver.GRPCService/Repository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCServiceServer).Repository(ctx, req.(*RepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GRPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nvidia.inferenceserver.GRPCService",
	HandlerType: (*GRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _GRPCService_Status_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _GRPCService_Health_Handler,
		},
		{
			MethodName: "Infer",
			Handler:    _GRPCService_Infer_Handler,
		},
		{
			MethodName: "ModelControl",
			Handler:    _GRPCService_ModelControl_Handler,
		},
		{
			MethodName: "SharedMemoryControl",
			Handler:    _GRPCService_SharedMemoryControl_Handler,
		},
		{
			MethodName: "Repository",
			Handler:    _GRPCService_Repository_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamInfer",
			Handler:       _GRPCService_StreamInfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc_service.proto",
}
