// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_status.proto

package nvidia_inferenceserver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//@@
//@@.. cpp:enum:: ModelReadyState
//@@
//@@   Readiness status for models.
//@@
type ModelReadyState int32

const (
	//@@  .. cpp:enumerator:: ModelReadyState::MODEL_UNKNOWN = 0
	//@@
	//@@     The model is in an unknown state. The model is not available for
	//@@     inferencing.
	//@@
	ModelReadyState_MODEL_UNKNOWN ModelReadyState = 0
	//@@  .. cpp:enumerator:: ModelReadyState::MODEL_READY = 1
	//@@
	//@@     The model is ready and available for inferencing.
	//@@
	ModelReadyState_MODEL_READY ModelReadyState = 1
	//@@  .. cpp:enumerator:: ModelReadyState::MODEL_UNAVAILABLE = 2
	//@@
	//@@     The model is unavailable, indicating that the model failed to
	//@@     load or has been implicitly or explicitly unloaded. The model is
	//@@     not available for inferencing.
	//@@
	ModelReadyState_MODEL_UNAVAILABLE ModelReadyState = 2
	//@@  .. cpp:enumerator:: ModelReadyState::MODEL_LOADING = 3
	//@@
	//@@     The model is being loaded by the inference server. The model is
	//@@     not available for inferencing.
	//@@
	ModelReadyState_MODEL_LOADING ModelReadyState = 3
	//@@  .. cpp:enumerator:: ModelReadyState::MODEL_UNLOADING = 4
	//@@
	//@@     The model is being unloaded by the inference server. The model is
	//@@     not available for inferencing.
	//@@
	ModelReadyState_MODEL_UNLOADING ModelReadyState = 4
)

var ModelReadyState_name = map[int32]string{
	0: "MODEL_UNKNOWN",
	1: "MODEL_READY",
	2: "MODEL_UNAVAILABLE",
	3: "MODEL_LOADING",
	4: "MODEL_UNLOADING",
}

var ModelReadyState_value = map[string]int32{
	"MODEL_UNKNOWN":     0,
	"MODEL_READY":       1,
	"MODEL_UNAVAILABLE": 2,
	"MODEL_LOADING":     3,
	"MODEL_UNLOADING":   4,
}

func (x ModelReadyState) String() string {
	return proto.EnumName(ModelReadyState_name, int32(x))
}

func (ModelReadyState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{0}
}

//@@
//@@.. cpp:enum:: ServerReadyState
//@@
//@@   Readiness status for the inference server.
//@@
type ServerReadyState int32

const (
	//@@  .. cpp:enumerator:: ServerReadyState::SERVER_INVALID = 0
	//@@
	//@@     The server is in an invalid state and will likely not
	//@@     response correctly to any requests.
	//@@
	ServerReadyState_SERVER_INVALID ServerReadyState = 0
	//@@  .. cpp:enumerator:: ServerReadyState::SERVER_INITIALIZING = 1
	//@@
	//@@     The server is initializing.
	//@@
	ServerReadyState_SERVER_INITIALIZING ServerReadyState = 1
	//@@  .. cpp:enumerator:: ServerReadyState::SERVER_READY = 2
	//@@
	//@@     The server is ready and accepting requests.
	//@@
	ServerReadyState_SERVER_READY ServerReadyState = 2
	//@@  .. cpp:enumerator:: ServerReadyState::SERVER_EXITING = 3
	//@@
	//@@     The server is exiting and will not respond to requests.
	//@@
	ServerReadyState_SERVER_EXITING ServerReadyState = 3
	//@@  .. cpp:enumerator:: ServerReadyState::SERVER_FAILED_TO_INITIALIZE = 10
	//@@
	//@@     The server did not initialize correctly. Most requests will fail.
	//@@
	ServerReadyState_SERVER_FAILED_TO_INITIALIZE ServerReadyState = 10
)

var ServerReadyState_name = map[int32]string{
	0:  "SERVER_INVALID",
	1:  "SERVER_INITIALIZING",
	2:  "SERVER_READY",
	3:  "SERVER_EXITING",
	10: "SERVER_FAILED_TO_INITIALIZE",
}

var ServerReadyState_value = map[string]int32{
	"SERVER_INVALID":              0,
	"SERVER_INITIALIZING":         1,
	"SERVER_READY":                2,
	"SERVER_EXITING":              3,
	"SERVER_FAILED_TO_INITIALIZE": 10,
}

func (x ServerReadyState) String() string {
	return proto.EnumName(ServerReadyState_name, int32(x))
}

func (ServerReadyState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{1}
}

//@@
//@@.. cpp:var:: message StatDuration
//@@
//@@   Statistic collecting a duration metric.
//@@
type StatDuration struct {
	//@@  .. cpp:var:: uint64 count
	//@@
	//@@     Cumulative number of times this metric occurred.
	//@@
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	//@@  .. cpp:var:: uint64 total_time_ns
	//@@
	//@@     Total collected duration of this metric in nanoseconds.
	//@@
	TotalTimeNs          uint64   `protobuf:"varint,2,opt,name=total_time_ns,json=totalTimeNs,proto3" json:"total_time_ns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatDuration) Reset()         { *m = StatDuration{} }
func (m *StatDuration) String() string { return proto.CompactTextString(m) }
func (*StatDuration) ProtoMessage()    {}
func (*StatDuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{0}
}

func (m *StatDuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatDuration.Unmarshal(m, b)
}
func (m *StatDuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatDuration.Marshal(b, m, deterministic)
}
func (m *StatDuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatDuration.Merge(m, src)
}
func (m *StatDuration) XXX_Size() int {
	return xxx_messageInfo_StatDuration.Size(m)
}
func (m *StatDuration) XXX_DiscardUnknown() {
	xxx_messageInfo_StatDuration.DiscardUnknown(m)
}

var xxx_messageInfo_StatDuration proto.InternalMessageInfo

func (m *StatDuration) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *StatDuration) GetTotalTimeNs() uint64 {
	if m != nil {
		return m.TotalTimeNs
	}
	return 0
}

//@@
//@@.. cpp:var:: message StatusRequestStats
//@@
//@@   Statistics collected for Status requests.
//@@
type StatusRequestStats struct {
	//@@  .. cpp:var:: StatDuration success
	//@@
	//@@     Total time required to handle successful Status requests, not
	//@@     including HTTP or gRPC endpoint termination time.
	//@@
	Success              *StatDuration `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StatusRequestStats) Reset()         { *m = StatusRequestStats{} }
func (m *StatusRequestStats) String() string { return proto.CompactTextString(m) }
func (*StatusRequestStats) ProtoMessage()    {}
func (*StatusRequestStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{1}
}

func (m *StatusRequestStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequestStats.Unmarshal(m, b)
}
func (m *StatusRequestStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequestStats.Marshal(b, m, deterministic)
}
func (m *StatusRequestStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequestStats.Merge(m, src)
}
func (m *StatusRequestStats) XXX_Size() int {
	return xxx_messageInfo_StatusRequestStats.Size(m)
}
func (m *StatusRequestStats) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequestStats.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequestStats proto.InternalMessageInfo

func (m *StatusRequestStats) GetSuccess() *StatDuration {
	if m != nil {
		return m.Success
	}
	return nil
}

//@@
//@@.. cpp:var:: message HealthRequestStats
//@@
//@@   Statistics collected for Health requests.
//@@
type HealthRequestStats struct {
	//@@  .. cpp:var:: StatDuration success
	//@@
	//@@     Total time required to handle successful Health requests, not
	//@@     including HTTP or gRPC endpoint termination time.
	//@@
	Success              *StatDuration `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HealthRequestStats) Reset()         { *m = HealthRequestStats{} }
func (m *HealthRequestStats) String() string { return proto.CompactTextString(m) }
func (*HealthRequestStats) ProtoMessage()    {}
func (*HealthRequestStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{2}
}

func (m *HealthRequestStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequestStats.Unmarshal(m, b)
}
func (m *HealthRequestStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequestStats.Marshal(b, m, deterministic)
}
func (m *HealthRequestStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequestStats.Merge(m, src)
}
func (m *HealthRequestStats) XXX_Size() int {
	return xxx_messageInfo_HealthRequestStats.Size(m)
}
func (m *HealthRequestStats) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequestStats.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequestStats proto.InternalMessageInfo

func (m *HealthRequestStats) GetSuccess() *StatDuration {
	if m != nil {
		return m.Success
	}
	return nil
}

//@@
//@@.. cpp:var:: message ModelControlRequestStats
//@@
//@@   Statistics collected for ModelControl requests.
//@@
type ModelControlRequestStats struct {
	//@@  .. cpp:var:: StatDuration success
	//@@
	//@@     Total time required to handle successful ModelControl requests, not
	//@@     including HTTP or gRPC endpoint termination time.
	//@@
	Success              *StatDuration `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ModelControlRequestStats) Reset()         { *m = ModelControlRequestStats{} }
func (m *ModelControlRequestStats) String() string { return proto.CompactTextString(m) }
func (*ModelControlRequestStats) ProtoMessage()    {}
func (*ModelControlRequestStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{3}
}

func (m *ModelControlRequestStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelControlRequestStats.Unmarshal(m, b)
}
func (m *ModelControlRequestStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelControlRequestStats.Marshal(b, m, deterministic)
}
func (m *ModelControlRequestStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelControlRequestStats.Merge(m, src)
}
func (m *ModelControlRequestStats) XXX_Size() int {
	return xxx_messageInfo_ModelControlRequestStats.Size(m)
}
func (m *ModelControlRequestStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelControlRequestStats.DiscardUnknown(m)
}

var xxx_messageInfo_ModelControlRequestStats proto.InternalMessageInfo

func (m *ModelControlRequestStats) GetSuccess() *StatDuration {
	if m != nil {
		return m.Success
	}
	return nil
}

//@@
//@@.. cpp:var:: message SharedMemoryControlRequestStats
//@@
//@@   Statistics collected for SharedMemoryControl requests.
//@@
type SharedMemoryControlRequestStats struct {
	//@@  .. cpp:var:: StatDuration success
	//@@
	//@@     Total time required to handle successful SharedMemoryControl
	//@@     requests, not including HTTP or gRPC endpoint termination time.
	//@@
	Success              *StatDuration `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SharedMemoryControlRequestStats) Reset()         { *m = SharedMemoryControlRequestStats{} }
func (m *SharedMemoryControlRequestStats) String() string { return proto.CompactTextString(m) }
func (*SharedMemoryControlRequestStats) ProtoMessage()    {}
func (*SharedMemoryControlRequestStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{4}
}

func (m *SharedMemoryControlRequestStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryControlRequestStats.Unmarshal(m, b)
}
func (m *SharedMemoryControlRequestStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryControlRequestStats.Marshal(b, m, deterministic)
}
func (m *SharedMemoryControlRequestStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryControlRequestStats.Merge(m, src)
}
func (m *SharedMemoryControlRequestStats) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryControlRequestStats.Size(m)
}
func (m *SharedMemoryControlRequestStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryControlRequestStats.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryControlRequestStats proto.InternalMessageInfo

func (m *SharedMemoryControlRequestStats) GetSuccess() *StatDuration {
	if m != nil {
		return m.Success
	}
	return nil
}

//@@
//@@.. cpp:var:: message RepositoryRequestStats
//@@
//@@   Statistics collected for Repository requests.
//@@
type RepositoryRequestStats struct {
	//@@  .. cpp:var:: StatDuration success
	//@@
	//@@     Total time required to handle successful Repository requests, not
	//@@     including HTTP or gRPC endpoint termination time.
	//@@
	Success              *StatDuration `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RepositoryRequestStats) Reset()         { *m = RepositoryRequestStats{} }
func (m *RepositoryRequestStats) String() string { return proto.CompactTextString(m) }
func (*RepositoryRequestStats) ProtoMessage()    {}
func (*RepositoryRequestStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{5}
}

func (m *RepositoryRequestStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryRequestStats.Unmarshal(m, b)
}
func (m *RepositoryRequestStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryRequestStats.Marshal(b, m, deterministic)
}
func (m *RepositoryRequestStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryRequestStats.Merge(m, src)
}
func (m *RepositoryRequestStats) XXX_Size() int {
	return xxx_messageInfo_RepositoryRequestStats.Size(m)
}
func (m *RepositoryRequestStats) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryRequestStats.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryRequestStats proto.InternalMessageInfo

func (m *RepositoryRequestStats) GetSuccess() *StatDuration {
	if m != nil {
		return m.Success
	}
	return nil
}

//@@
//@@.. cpp:var:: message InferRequestStats
//@@
//@@   Statistics collected for Infer requests.
//@@
type InferRequestStats struct {
	//@@  .. cpp:var:: StatDuration success
	//@@
	//@@     Total time required to handle successful Infer requests, not
	//@@     including HTTP or GRPC endpoint handling time.
	//@@
	Success *StatDuration `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	//@@  .. cpp:var:: StatDuration failed
	//@@
	//@@     Total time required to handle failed Infer requests, not
	//@@     including HTTP or GRPC endpoint handling time.
	//@@
	Failed *StatDuration `protobuf:"bytes,2,opt,name=failed,proto3" json:"failed,omitempty"`
	//@@  .. cpp:var:: StatDuration compute
	//@@
	//@@     Time required to run inferencing for an inference request;
	//@@     including time copying input tensors to GPU memory, time
	//@@     executing the model, and time copying output tensors from GPU
	//@@     memory.
	//@@
	Compute *StatDuration `protobuf:"bytes,3,opt,name=compute,proto3" json:"compute,omitempty"`
	//@@  .. cpp:var:: StatDuration queue
	//@@
	//@@     Time an inference request waits in scheduling queue for an
	//@@     available model instance.
	//@@
	Queue                *StatDuration `protobuf:"bytes,4,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InferRequestStats) Reset()         { *m = InferRequestStats{} }
func (m *InferRequestStats) String() string { return proto.CompactTextString(m) }
func (*InferRequestStats) ProtoMessage()    {}
func (*InferRequestStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{6}
}

func (m *InferRequestStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InferRequestStats.Unmarshal(m, b)
}
func (m *InferRequestStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InferRequestStats.Marshal(b, m, deterministic)
}
func (m *InferRequestStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InferRequestStats.Merge(m, src)
}
func (m *InferRequestStats) XXX_Size() int {
	return xxx_messageInfo_InferRequestStats.Size(m)
}
func (m *InferRequestStats) XXX_DiscardUnknown() {
	xxx_messageInfo_InferRequestStats.DiscardUnknown(m)
}

var xxx_messageInfo_InferRequestStats proto.InternalMessageInfo

func (m *InferRequestStats) GetSuccess() *StatDuration {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *InferRequestStats) GetFailed() *StatDuration {
	if m != nil {
		return m.Failed
	}
	return nil
}

func (m *InferRequestStats) GetCompute() *StatDuration {
	if m != nil {
		return m.Compute
	}
	return nil
}

func (m *InferRequestStats) GetQueue() *StatDuration {
	if m != nil {
		return m.Queue
	}
	return nil
}

//@@
//@@.. cpp:enum:: ModelReadyStateReason
//@@
//@@   Detail associated with a model's readiness status.
//@@
type ModelReadyStateReason struct {
	//@@  .. cpp:var:: string message
	//@@
	//@@     The message that explains the cause of being in the current readiness
	//@@     state.
	//@@
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelReadyStateReason) Reset()         { *m = ModelReadyStateReason{} }
func (m *ModelReadyStateReason) String() string { return proto.CompactTextString(m) }
func (*ModelReadyStateReason) ProtoMessage()    {}
func (*ModelReadyStateReason) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{7}
}

func (m *ModelReadyStateReason) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelReadyStateReason.Unmarshal(m, b)
}
func (m *ModelReadyStateReason) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelReadyStateReason.Marshal(b, m, deterministic)
}
func (m *ModelReadyStateReason) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelReadyStateReason.Merge(m, src)
}
func (m *ModelReadyStateReason) XXX_Size() int {
	return xxx_messageInfo_ModelReadyStateReason.Size(m)
}
func (m *ModelReadyStateReason) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelReadyStateReason.DiscardUnknown(m)
}

var xxx_messageInfo_ModelReadyStateReason proto.InternalMessageInfo

func (m *ModelReadyStateReason) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//@@
//@@.. cpp:var:: message ModelVersionStatus
//@@
//@@   Status for a version of a model.
//@@
type ModelVersionStatus struct {
	//@@  .. cpp:var:: ModelReadyState ready_state
	//@@
	//@@     Current readiness state for the model.
	//@@
	ReadyState ModelReadyState `protobuf:"varint,1,opt,name=ready_state,json=readyState,proto3,enum=nvidia.inferenceserver.ModelReadyState" json:"ready_state,omitempty"`
	//@@  .. cpp:var:: ModelReadyStateReason ready_state_reason
	//@@
	//@@     Supplemental information regarding the current readiness state.
	//@@
	ReadyStateReason *ModelReadyStateReason `protobuf:"bytes,5,opt,name=ready_state_reason,json=readyStateReason,proto3" json:"ready_state_reason,omitempty"`
	//@@  .. cpp:var:: map<uint32, InferRequestStats> infer_stats
	//@@
	//@@     Inference statistics for the model, as a map from batch size
	//@@     to the statistics. A batch size will not occur in the map
	//@@     unless there has been at least one inference request of
	//@@     that batch size.
	//@@
	InferStats map[uint32]*InferRequestStats `protobuf:"bytes,2,rep,name=infer_stats,json=inferStats,proto3" json:"infer_stats,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//@@  .. cpp:var:: uint64 model_execution_count
	//@@
	//@@     Cumulative number of model executions performed for the
	//@@     model. A single model execution performs inferencing for
	//@@     the entire request batch and can perform inferencing for multiple
	//@@     requests if dynamic batching is enabled.
	//@@
	ModelExecutionCount uint64 `protobuf:"varint,3,opt,name=model_execution_count,json=modelExecutionCount,proto3" json:"model_execution_count,omitempty"`
	//@@  .. cpp:var:: uint64 model_inference_count
	//@@
	//@@     Cumulative number of model inferences performed for the
	//@@     model. Each inference in a batched request is counted as
	//@@     an individual inference.
	//@@
	ModelInferenceCount uint64 `protobuf:"varint,4,opt,name=model_inference_count,json=modelInferenceCount,proto3" json:"model_inference_count,omitempty"`
	//@@  .. cpp:var:: uint64 last_inference_timestamp_milliseconds
	//@@
	//@@     The timestamp of the last inference request made for this model,
	//@@     given as milliseconds since the epoch.
	//@@
	LastInferenceTimestampMilliseconds uint64   `protobuf:"varint,6,opt,name=last_inference_timestamp_milliseconds,json=lastInferenceTimestampMilliseconds,proto3" json:"last_inference_timestamp_milliseconds,omitempty"`
	XXX_NoUnkeyedLiteral               struct{} `json:"-"`
	XXX_unrecognized                   []byte   `json:"-"`
	XXX_sizecache                      int32    `json:"-"`
}

func (m *ModelVersionStatus) Reset()         { *m = ModelVersionStatus{} }
func (m *ModelVersionStatus) String() string { return proto.CompactTextString(m) }
func (*ModelVersionStatus) ProtoMessage()    {}
func (*ModelVersionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{8}
}

func (m *ModelVersionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelVersionStatus.Unmarshal(m, b)
}
func (m *ModelVersionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelVersionStatus.Marshal(b, m, deterministic)
}
func (m *ModelVersionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelVersionStatus.Merge(m, src)
}
func (m *ModelVersionStatus) XXX_Size() int {
	return xxx_messageInfo_ModelVersionStatus.Size(m)
}
func (m *ModelVersionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelVersionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ModelVersionStatus proto.InternalMessageInfo

func (m *ModelVersionStatus) GetReadyState() ModelReadyState {
	if m != nil {
		return m.ReadyState
	}
	return ModelReadyState_MODEL_UNKNOWN
}

func (m *ModelVersionStatus) GetReadyStateReason() *ModelReadyStateReason {
	if m != nil {
		return m.ReadyStateReason
	}
	return nil
}

func (m *ModelVersionStatus) GetInferStats() map[uint32]*InferRequestStats {
	if m != nil {
		return m.InferStats
	}
	return nil
}

func (m *ModelVersionStatus) GetModelExecutionCount() uint64 {
	if m != nil {
		return m.ModelExecutionCount
	}
	return 0
}

func (m *ModelVersionStatus) GetModelInferenceCount() uint64 {
	if m != nil {
		return m.ModelInferenceCount
	}
	return 0
}

func (m *ModelVersionStatus) GetLastInferenceTimestampMilliseconds() uint64 {
	if m != nil {
		return m.LastInferenceTimestampMilliseconds
	}
	return 0
}

//@@
//@@.. cpp:var:: message ModelStatus
//@@
//@@   Status for a model.
//@@
type ModelStatus struct {
	//@@  .. cpp:var:: ModelConfig config
	//@@
	//@@     The configuration for the model.
	//@@
	Config *ModelConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	//@@  .. cpp:var:: map<int64, ModelVersionStatus> version_status
	//@@
	//@@     Duration statistics for each version of the model, as a map
	//@@     from version to the status. A version will not occur in the map
	//@@     unless there has been at least one inference request of
	//@@     that model version. A version of -1 indicates the status is
	//@@     for requests for which the version could not be determined.
	//@@
	VersionStatus        map[int64]*ModelVersionStatus `protobuf:"bytes,2,rep,name=version_status,json=versionStatus,proto3" json:"version_status,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ModelStatus) Reset()         { *m = ModelStatus{} }
func (m *ModelStatus) String() string { return proto.CompactTextString(m) }
func (*ModelStatus) ProtoMessage()    {}
func (*ModelStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{9}
}

func (m *ModelStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelStatus.Unmarshal(m, b)
}
func (m *ModelStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelStatus.Marshal(b, m, deterministic)
}
func (m *ModelStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelStatus.Merge(m, src)
}
func (m *ModelStatus) XXX_Size() int {
	return xxx_messageInfo_ModelStatus.Size(m)
}
func (m *ModelStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ModelStatus proto.InternalMessageInfo

func (m *ModelStatus) GetConfig() *ModelConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ModelStatus) GetVersionStatus() map[int64]*ModelVersionStatus {
	if m != nil {
		return m.VersionStatus
	}
	return nil
}

//@@.. cpp:var:: message SharedMemoryRegion
//@@
//@@   The meta-data for the shared memory region registered in the inference
//@@   server.
//@@
type SharedMemoryRegion struct {
	//@@
	//@@  .. cpp:var:: string name
	//@@
	//@@     The name for this shared memory region.
	//@@
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//@@  .. cpp:var:: oneof shared_memory_types
	//@@
	//@@     Types of shared memory identifiers
	//@@
	//
	// Types that are valid to be assigned to SharedMemoryTypes:
	//	*SharedMemoryRegion_SystemSharedMemory_
	//	*SharedMemoryRegion_CudaSharedMemory_
	SharedMemoryTypes isSharedMemoryRegion_SharedMemoryTypes `protobuf_oneof:"shared_memory_types"`
	//@@  .. cpp:var:: uint64 byte_size
	//@@
	//@@     Size of the shared memory block, in bytes.
	//@@
	ByteSize             uint64   `protobuf:"varint,5,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedMemoryRegion) Reset()         { *m = SharedMemoryRegion{} }
func (m *SharedMemoryRegion) String() string { return proto.CompactTextString(m) }
func (*SharedMemoryRegion) ProtoMessage()    {}
func (*SharedMemoryRegion) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{10}
}

func (m *SharedMemoryRegion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryRegion.Unmarshal(m, b)
}
func (m *SharedMemoryRegion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryRegion.Marshal(b, m, deterministic)
}
func (m *SharedMemoryRegion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryRegion.Merge(m, src)
}
func (m *SharedMemoryRegion) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryRegion.Size(m)
}
func (m *SharedMemoryRegion) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryRegion.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryRegion proto.InternalMessageInfo

func (m *SharedMemoryRegion) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isSharedMemoryRegion_SharedMemoryTypes interface {
	isSharedMemoryRegion_SharedMemoryTypes()
}

type SharedMemoryRegion_SystemSharedMemory_ struct {
	SystemSharedMemory *SharedMemoryRegion_SystemSharedMemory `protobuf:"bytes,2,opt,name=system_shared_memory,json=systemSharedMemory,proto3,oneof"`
}

type SharedMemoryRegion_CudaSharedMemory_ struct {
	CudaSharedMemory *SharedMemoryRegion_CudaSharedMemory `protobuf:"bytes,3,opt,name=cuda_shared_memory,json=cudaSharedMemory,proto3,oneof"`
}

func (*SharedMemoryRegion_SystemSharedMemory_) isSharedMemoryRegion_SharedMemoryTypes() {}

func (*SharedMemoryRegion_CudaSharedMemory_) isSharedMemoryRegion_SharedMemoryTypes() {}

func (m *SharedMemoryRegion) GetSharedMemoryTypes() isSharedMemoryRegion_SharedMemoryTypes {
	if m != nil {
		return m.SharedMemoryTypes
	}
	return nil
}

func (m *SharedMemoryRegion) GetSystemSharedMemory() *SharedMemoryRegion_SystemSharedMemory {
	if x, ok := m.GetSharedMemoryTypes().(*SharedMemoryRegion_SystemSharedMemory_); ok {
		return x.SystemSharedMemory
	}
	return nil
}

func (m *SharedMemoryRegion) GetCudaSharedMemory() *SharedMemoryRegion_CudaSharedMemory {
	if x, ok := m.GetSharedMemoryTypes().(*SharedMemoryRegion_CudaSharedMemory_); ok {
		return x.CudaSharedMemory
	}
	return nil
}

func (m *SharedMemoryRegion) GetByteSize() uint64 {
	if m != nil {
		return m.ByteSize
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SharedMemoryRegion) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SharedMemoryRegion_SystemSharedMemory_)(nil),
		(*SharedMemoryRegion_CudaSharedMemory_)(nil),
	}
}

type SharedMemoryRegion_SystemSharedMemory struct {
	//@@  .. cpp:var:: string shared_memory_key
	//@@
	//@@     The name of the shared memory region that holds the input data
	//@@     (or where the output data should be written).
	//@@
	SharedMemoryKey string `protobuf:"bytes,1,opt,name=shared_memory_key,json=sharedMemoryKey,proto3" json:"shared_memory_key,omitempty"`
	//@@  .. cpp:var:: uint64 offset
	//@@
	//@@     This is the offset of the shared memory block from the start
	//@@     of the shared memory region.
	//@@     start = offset, end = offset + byte_size;
	//@@
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedMemoryRegion_SystemSharedMemory) Reset()         { *m = SharedMemoryRegion_SystemSharedMemory{} }
func (m *SharedMemoryRegion_SystemSharedMemory) String() string { return proto.CompactTextString(m) }
func (*SharedMemoryRegion_SystemSharedMemory) ProtoMessage()    {}
func (*SharedMemoryRegion_SystemSharedMemory) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{10, 0}
}

func (m *SharedMemoryRegion_SystemSharedMemory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryRegion_SystemSharedMemory.Unmarshal(m, b)
}
func (m *SharedMemoryRegion_SystemSharedMemory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryRegion_SystemSharedMemory.Marshal(b, m, deterministic)
}
func (m *SharedMemoryRegion_SystemSharedMemory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryRegion_SystemSharedMemory.Merge(m, src)
}
func (m *SharedMemoryRegion_SystemSharedMemory) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryRegion_SystemSharedMemory.Size(m)
}
func (m *SharedMemoryRegion_SystemSharedMemory) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryRegion_SystemSharedMemory.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryRegion_SystemSharedMemory proto.InternalMessageInfo

func (m *SharedMemoryRegion_SystemSharedMemory) GetSharedMemoryKey() string {
	if m != nil {
		return m.SharedMemoryKey
	}
	return ""
}

func (m *SharedMemoryRegion_SystemSharedMemory) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SharedMemoryRegion_CudaSharedMemory struct {
	//@@  .. cpp:var:: int64 device_id
	//@@
	//@@     The GPU device ID on which the cudaIPC handle was created.
	//@@
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedMemoryRegion_CudaSharedMemory) Reset()         { *m = SharedMemoryRegion_CudaSharedMemory{} }
func (m *SharedMemoryRegion_CudaSharedMemory) String() string { return proto.CompactTextString(m) }
func (*SharedMemoryRegion_CudaSharedMemory) ProtoMessage()    {}
func (*SharedMemoryRegion_CudaSharedMemory) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{10, 1}
}

func (m *SharedMemoryRegion_CudaSharedMemory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryRegion_CudaSharedMemory.Unmarshal(m, b)
}
func (m *SharedMemoryRegion_CudaSharedMemory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryRegion_CudaSharedMemory.Marshal(b, m, deterministic)
}
func (m *SharedMemoryRegion_CudaSharedMemory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryRegion_CudaSharedMemory.Merge(m, src)
}
func (m *SharedMemoryRegion_CudaSharedMemory) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryRegion_CudaSharedMemory.Size(m)
}
func (m *SharedMemoryRegion_CudaSharedMemory) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryRegion_CudaSharedMemory.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryRegion_CudaSharedMemory proto.InternalMessageInfo

func (m *SharedMemoryRegion_CudaSharedMemory) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

//@@
//@@.. cpp:var:: message ServerStatus
//@@
//@@   Status for the inference server.
//@@
type ServerStatus struct {
	//@@  .. cpp:var:: string id
	//@@
	//@@     The server's ID.
	//@@
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//@@  .. cpp:var:: string version
	//@@
	//@@     The server's version.
	//@@
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	//@@  .. cpp:var:: ServerReadyState ready_state
	//@@
	//@@     Current readiness state for the server.
	//@@
	ReadyState ServerReadyState `protobuf:"varint,7,opt,name=ready_state,json=readyState,proto3,enum=nvidia.inferenceserver.ServerReadyState" json:"ready_state,omitempty"`
	//@@  .. cpp:var:: uint64 uptime_ns
	//@@
	//@@     Server uptime in nanoseconds.
	//@@
	UptimeNs uint64 `protobuf:"varint,3,opt,name=uptime_ns,json=uptimeNs,proto3" json:"uptime_ns,omitempty"`
	//@@  .. cpp:var:: map<string, ModelStatus> model_status
	//@@
	//@@     Status for each model, as a map from model name to the
	//@@     status.
	//@@
	ModelStatus map[string]*ModelStatus `protobuf:"bytes,4,rep,name=model_status,json=modelStatus,proto3" json:"model_status,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//@@  .. cpp:var:: StatusRequestStats status_stats
	//@@
	//@@     Statistics for Status requests.
	//@@
	StatusStats *StatusRequestStats `protobuf:"bytes,5,opt,name=status_stats,json=statusStats,proto3" json:"status_stats,omitempty"`
	//@@  .. cpp:var:: HealthRequestStats health_stats
	//@@
	//@@     Statistics for Health requests.
	//@@
	HealthStats *HealthRequestStats `protobuf:"bytes,8,opt,name=health_stats,json=healthStats,proto3" json:"health_stats,omitempty"`
	//@@  .. cpp:var:: ModelControlRequestStats model_control_stats
	//@@
	//@@     Statistics for ModelControl requests.
	//@@
	ModelControlStats *ModelControlRequestStats `protobuf:"bytes,9,opt,name=model_control_stats,json=modelControlStats,proto3" json:"model_control_stats,omitempty"`
	//@@  .. cpp:var:: SharedMemoryControlRequestStats shm_control_stats
	//@@
	//@@     Statistics for SharedMemoryControl requests.
	//@@
	ShmControlStats *SharedMemoryControlRequestStats `protobuf:"bytes,10,opt,name=shm_control_stats,json=shmControlStats,proto3" json:"shm_control_stats,omitempty"`
	//@@  .. cpp:var:: RepositoryRequestStats repository_stats
	//@@
	//@@     Statistics for Repository requests.
	//@@
	RepositoryStats      *RepositoryRequestStats `protobuf:"bytes,11,opt,name=repository_stats,json=repositoryStats,proto3" json:"repository_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ServerStatus) Reset()         { *m = ServerStatus{} }
func (m *ServerStatus) String() string { return proto.CompactTextString(m) }
func (*ServerStatus) ProtoMessage()    {}
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{11}
}

func (m *ServerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatus.Unmarshal(m, b)
}
func (m *ServerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatus.Marshal(b, m, deterministic)
}
func (m *ServerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatus.Merge(m, src)
}
func (m *ServerStatus) XXX_Size() int {
	return xxx_messageInfo_ServerStatus.Size(m)
}
func (m *ServerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatus proto.InternalMessageInfo

func (m *ServerStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServerStatus) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServerStatus) GetReadyState() ServerReadyState {
	if m != nil {
		return m.ReadyState
	}
	return ServerReadyState_SERVER_INVALID
}

func (m *ServerStatus) GetUptimeNs() uint64 {
	if m != nil {
		return m.UptimeNs
	}
	return 0
}

func (m *ServerStatus) GetModelStatus() map[string]*ModelStatus {
	if m != nil {
		return m.ModelStatus
	}
	return nil
}

func (m *ServerStatus) GetStatusStats() *StatusRequestStats {
	if m != nil {
		return m.StatusStats
	}
	return nil
}

func (m *ServerStatus) GetHealthStats() *HealthRequestStats {
	if m != nil {
		return m.HealthStats
	}
	return nil
}

func (m *ServerStatus) GetModelControlStats() *ModelControlRequestStats {
	if m != nil {
		return m.ModelControlStats
	}
	return nil
}

func (m *ServerStatus) GetShmControlStats() *SharedMemoryControlRequestStats {
	if m != nil {
		return m.ShmControlStats
	}
	return nil
}

func (m *ServerStatus) GetRepositoryStats() *RepositoryRequestStats {
	if m != nil {
		return m.RepositoryStats
	}
	return nil
}

//@@
//@@.. cpp:var:: message SharedMemoryStatus
//@@
//@@   Shared memory status for the inference server.
//@@
type SharedMemoryStatus struct {
	//@@
	//@@  .. cpp:var:: SharedMemoryRegion shared_memory_region (repeated)
	//@@
	//@@     The list of active/registered shared memory regions.
	//@@
	SharedMemoryRegion   []*SharedMemoryRegion `protobuf:"bytes,2,rep,name=shared_memory_region,json=sharedMemoryRegion,proto3" json:"shared_memory_region,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SharedMemoryStatus) Reset()         { *m = SharedMemoryStatus{} }
func (m *SharedMemoryStatus) String() string { return proto.CompactTextString(m) }
func (*SharedMemoryStatus) ProtoMessage()    {}
func (*SharedMemoryStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{12}
}

func (m *SharedMemoryStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedMemoryStatus.Unmarshal(m, b)
}
func (m *SharedMemoryStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedMemoryStatus.Marshal(b, m, deterministic)
}
func (m *SharedMemoryStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedMemoryStatus.Merge(m, src)
}
func (m *SharedMemoryStatus) XXX_Size() int {
	return xxx_messageInfo_SharedMemoryStatus.Size(m)
}
func (m *SharedMemoryStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedMemoryStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SharedMemoryStatus proto.InternalMessageInfo

func (m *SharedMemoryStatus) GetSharedMemoryRegion() []*SharedMemoryRegion {
	if m != nil {
		return m.SharedMemoryRegion
	}
	return nil
}

//@@
//@@.. cpp:var:: message ModelRepositoryIndex
//@@
//@@   Index of the model repository monitored by the inference server.
//@@
type ModelRepositoryIndex struct {
	//@@
	//@@  .. cpp:var:: ModelEntry models (repeated)
	//@@
	//@@     The list of models in the model repository.
	//@@
	Models               []*ModelRepositoryIndex_ModelEntry `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ModelRepositoryIndex) Reset()         { *m = ModelRepositoryIndex{} }
func (m *ModelRepositoryIndex) String() string { return proto.CompactTextString(m) }
func (*ModelRepositoryIndex) ProtoMessage()    {}
func (*ModelRepositoryIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{13}
}

func (m *ModelRepositoryIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelRepositoryIndex.Unmarshal(m, b)
}
func (m *ModelRepositoryIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelRepositoryIndex.Marshal(b, m, deterministic)
}
func (m *ModelRepositoryIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelRepositoryIndex.Merge(m, src)
}
func (m *ModelRepositoryIndex) XXX_Size() int {
	return xxx_messageInfo_ModelRepositoryIndex.Size(m)
}
func (m *ModelRepositoryIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelRepositoryIndex.DiscardUnknown(m)
}

var xxx_messageInfo_ModelRepositoryIndex proto.InternalMessageInfo

func (m *ModelRepositoryIndex) GetModels() []*ModelRepositoryIndex_ModelEntry {
	if m != nil {
		return m.Models
	}
	return nil
}

//@@
//@@  .. cpp:var:: message ModelEntry
//@@
//@@     The basic information for a model.
//@@
type ModelRepositoryIndex_ModelEntry struct {
	//@@    .. cpp:var:: string name
	//@@
	//@@       The model's name.
	//@@
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelRepositoryIndex_ModelEntry) Reset()         { *m = ModelRepositoryIndex_ModelEntry{} }
func (m *ModelRepositoryIndex_ModelEntry) String() string { return proto.CompactTextString(m) }
func (*ModelRepositoryIndex_ModelEntry) ProtoMessage()    {}
func (*ModelRepositoryIndex_ModelEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1c8274bb4c3bd67, []int{13, 0}
}

func (m *ModelRepositoryIndex_ModelEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelRepositoryIndex_ModelEntry.Unmarshal(m, b)
}
func (m *ModelRepositoryIndex_ModelEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelRepositoryIndex_ModelEntry.Marshal(b, m, deterministic)
}
func (m *ModelRepositoryIndex_ModelEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelRepositoryIndex_ModelEntry.Merge(m, src)
}
func (m *ModelRepositoryIndex_ModelEntry) XXX_Size() int {
	return xxx_messageInfo_ModelRepositoryIndex_ModelEntry.Size(m)
}
func (m *ModelRepositoryIndex_ModelEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelRepositoryIndex_ModelEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ModelRepositoryIndex_ModelEntry proto.InternalMessageInfo

func (m *ModelRepositoryIndex_ModelEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("nvidia.inferenceserver.ModelReadyState", ModelReadyState_name, ModelReadyState_value)
	proto.RegisterEnum("nvidia.inferenceserver.ServerReadyState", ServerReadyState_name, ServerReadyState_value)
	proto.RegisterType((*StatDuration)(nil), "nvidia.inferenceserver.StatDuration")
	proto.RegisterType((*StatusRequestStats)(nil), "nvidia.inferenceserver.StatusRequestStats")
	proto.RegisterType((*HealthRequestStats)(nil), "nvidia.inferenceserver.HealthRequestStats")
	proto.RegisterType((*ModelControlRequestStats)(nil), "nvidia.inferenceserver.ModelControlRequestStats")
	proto.RegisterType((*SharedMemoryControlRequestStats)(nil), "nvidia.inferenceserver.SharedMemoryControlRequestStats")
	proto.RegisterType((*RepositoryRequestStats)(nil), "nvidia.inferenceserver.RepositoryRequestStats")
	proto.RegisterType((*InferRequestStats)(nil), "nvidia.inferenceserver.InferRequestStats")
	proto.RegisterType((*ModelReadyStateReason)(nil), "nvidia.inferenceserver.ModelReadyStateReason")
	proto.RegisterType((*ModelVersionStatus)(nil), "nvidia.inferenceserver.ModelVersionStatus")
	proto.RegisterMapType((map[uint32]*InferRequestStats)(nil), "nvidia.inferenceserver.ModelVersionStatus.InferStatsEntry")
	proto.RegisterType((*ModelStatus)(nil), "nvidia.inferenceserver.ModelStatus")
	proto.RegisterMapType((map[int64]*ModelVersionStatus)(nil), "nvidia.inferenceserver.ModelStatus.VersionStatusEntry")
	proto.RegisterType((*SharedMemoryRegion)(nil), "nvidia.inferenceserver.SharedMemoryRegion")
	proto.RegisterType((*SharedMemoryRegion_SystemSharedMemory)(nil), "nvidia.inferenceserver.SharedMemoryRegion.SystemSharedMemory")
	proto.RegisterType((*SharedMemoryRegion_CudaSharedMemory)(nil), "nvidia.inferenceserver.SharedMemoryRegion.CudaSharedMemory")
	proto.RegisterType((*ServerStatus)(nil), "nvidia.inferenceserver.ServerStatus")
	proto.RegisterMapType((map[string]*ModelStatus)(nil), "nvidia.inferenceserver.ServerStatus.ModelStatusEntry")
	proto.RegisterType((*SharedMemoryStatus)(nil), "nvidia.inferenceserver.SharedMemoryStatus")
	proto.RegisterType((*ModelRepositoryIndex)(nil), "nvidia.inferenceserver.ModelRepositoryIndex")
	proto.RegisterType((*ModelRepositoryIndex_ModelEntry)(nil), "nvidia.inferenceserver.ModelRepositoryIndex.ModelEntry")
}

func init() { proto.RegisterFile("server_status.proto", fileDescriptor_d1c8274bb4c3bd67) }

var fileDescriptor_d1c8274bb4c3bd67 = []byte{
	// 1175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0x6e, 0x2e, 0x4d, 0x9b, 0xe3, 0xb4, 0x71, 0x27, 0x6d, 0x89, 0xd2, 0x87, 0x5d, 0x65, 0x41,
	0x94, 0x4a, 0x04, 0x28, 0xe2, 0xd6, 0xe5, 0x96, 0x6d, 0x02, 0xb5, 0x36, 0x49, 0xc5, 0x24, 0x94,
	0xee, 0x2e, 0xc8, 0x78, 0xed, 0x69, 0x63, 0x6d, 0x6c, 0xa7, 0x9e, 0x71, 0xb4, 0xd9, 0x1f, 0x80,
	0xc4, 0x03, 0xcf, 0x3c, 0xf2, 0x4b, 0x78, 0xe6, 0x6f, 0x21, 0xcf, 0x8c, 0x53, 0xc7, 0xb9, 0x90,
	0x4a, 0xe5, 0xa9, 0xf1, 0x99, 0xf3, 0x7d, 0x67, 0x7c, 0x2e, 0x9f, 0x4f, 0xa1, 0x44, 0x89, 0x3f,
	0x22, 0xbe, 0x4e, 0x99, 0xc1, 0x02, 0x5a, 0x1b, 0xfa, 0x1e, 0xf3, 0xd0, 0xbe, 0x3b, 0xb2, 0x2d,
	0xdb, 0xa8, 0xd9, 0xee, 0x15, 0xf1, 0x89, 0x6b, 0x12, 0xe1, 0x54, 0x41, 0x8e, 0x67, 0x91, 0x81,
	0x6e, 0x7a, 0xee, 0x95, 0x7d, 0x2d, 0x7c, 0xab, 0x67, 0x50, 0xe8, 0x32, 0x83, 0x35, 0x02, 0xdf,
	0x60, 0xb6, 0xe7, 0xa2, 0x5d, 0x58, 0x37, 0xbd, 0xc0, 0x65, 0xe5, 0xd4, 0xc3, 0xd4, 0x61, 0x16,
	0x8b, 0x07, 0x54, 0x85, 0x2d, 0xe6, 0x31, 0x63, 0xa0, 0x33, 0xdb, 0x21, 0xba, 0x4b, 0xcb, 0x69,
	0x7e, 0xaa, 0x70, 0x63, 0xcf, 0x76, 0x48, 0x87, 0x56, 0x7b, 0x80, 0xba, 0xfc, 0x16, 0x98, 0xdc,
	0x04, 0x84, 0xb2, 0xf0, 0x81, 0xa2, 0xaf, 0x61, 0x83, 0x06, 0xa6, 0x49, 0x28, 0xe5, 0x8c, 0xca,
	0xf1, 0xdb, 0xb5, 0xf9, 0xb7, 0xab, 0xc5, 0xaf, 0x81, 0x23, 0x50, 0xc8, 0x7a, 0x46, 0x8c, 0x01,
	0xeb, 0xdf, 0x2b, 0xeb, 0x73, 0x28, 0xb7, 0xc3, 0x5c, 0x9c, 0x7a, 0x2e, 0xf3, 0xbd, 0xc1, 0xbd,
	0x72, 0x1b, 0xf0, 0xa0, 0xdb, 0x37, 0x7c, 0x62, 0xb5, 0x89, 0xe3, 0xf9, 0xe3, 0xff, 0x23, 0xc4,
	0x25, 0xec, 0x63, 0x32, 0xf4, 0xa8, 0xcd, 0x3c, 0x7f, 0x7c, 0xaf, 0xcc, 0x7f, 0xa4, 0x61, 0x47,
	0x0b, 0x3d, 0xef, 0x93, 0x15, 0x7d, 0x09, 0xb9, 0x2b, 0xc3, 0x1e, 0x10, 0x8b, 0xf7, 0xcd, 0xaa,
	0x70, 0x89, 0x09, 0xa3, 0x9b, 0x9e, 0x33, 0x0c, 0x18, 0x29, 0x67, 0xee, 0x12, 0x5d, 0x82, 0xd0,
	0x09, 0xac, 0xdf, 0x04, 0x24, 0x20, 0xe5, 0xec, 0x1d, 0xd0, 0x02, 0x52, 0xfd, 0x08, 0xf6, 0x78,
	0xa3, 0x60, 0x62, 0x58, 0xe3, 0xd0, 0x81, 0x60, 0x62, 0x50, 0xcf, 0x45, 0x65, 0xd8, 0x70, 0x08,
	0xa5, 0xc6, 0x35, 0xe1, 0x29, 0xc9, 0xe3, 0xe8, 0xb1, 0xfa, 0x77, 0x16, 0x10, 0xc7, 0x5c, 0x10,
	0x9f, 0xda, 0x9e, 0x2b, 0x86, 0x02, 0x9d, 0x81, 0xe2, 0x87, 0x24, 0x7c, 0x54, 0x05, 0x68, 0xfb,
	0xf8, 0xdd, 0x45, 0x77, 0x49, 0x06, 0x05, 0x7f, 0xf2, 0x1b, 0xbd, 0x00, 0x14, 0x63, 0xd2, 0x7d,
	0x7e, 0xa1, 0xf2, 0x3a, 0x7f, 0xb9, 0xf7, 0x57, 0x25, 0xe4, 0x20, 0xac, 0xfa, 0xc9, 0xf7, 0x7a,
	0x01, 0x0a, 0x87, 0x72, 0xf2, 0x70, 0xce, 0x33, 0x87, 0xca, 0xf1, 0xc9, 0x52, 0xd6, 0xa9, 0xf7,
	0xac, 0xf1, 0xee, 0xe1, 0x6d, 0xd3, 0x74, 0x99, 0x3f, 0xc6, 0x60, 0x4f, 0x0c, 0xe8, 0x18, 0xf6,
	0x84, 0x04, 0x91, 0xd7, 0xc4, 0x0c, 0xc2, 0x3c, 0xeb, 0x42, 0x6c, 0x32, 0x5c, 0x4e, 0x4a, 0xfc,
	0xb0, 0x19, 0x9d, 0x9d, 0x72, 0xe9, 0x99, 0x60, 0x26, 0xb1, 0x25, 0x26, 0x1b, 0xc3, 0x68, 0xd1,
	0x99, 0xc0, 0xfc, 0x00, 0xef, 0x0c, 0x0c, 0xca, 0x62, 0x90, 0x50, 0xb7, 0x28, 0x33, 0x9c, 0xa1,
	0xee, 0xd8, 0x83, 0x81, 0x4d, 0x89, 0xe9, 0xb9, 0x16, 0x2d, 0xe7, 0x38, 0x47, 0x35, 0x74, 0x9e,
	0x50, 0xf4, 0x22, 0xd7, 0x76, 0xcc, 0xb3, 0xd2, 0x87, 0x62, 0xe2, 0xcd, 0x90, 0x0a, 0x99, 0x57,
	0x64, 0xcc, 0x2b, 0xb9, 0x85, 0xc3, 0x9f, 0xe8, 0x1b, 0x58, 0x1f, 0x19, 0x83, 0x80, 0xc8, 0x36,
	0x7f, 0x6f, 0x51, 0xda, 0x66, 0x26, 0x0c, 0x0b, 0xdc, 0x49, 0xfa, 0xf3, 0x54, 0xf5, 0xcf, 0x34,
	0x28, 0x3c, 0xaf, 0xb2, 0x71, 0x1e, 0x43, 0x4e, 0x28, 0xb6, 0x9c, 0xbd, 0x47, 0x4b, 0x8b, 0x71,
	0xca, 0x5d, 0xb1, 0x84, 0xa0, 0x5f, 0x60, 0x7b, 0x24, 0xca, 0x23, 0x3f, 0x11, 0xb2, 0xa2, 0x9f,
	0x2e, 0x25, 0x91, 0xa5, 0x9c, 0x2a, 0xac, 0xa8, 0xe6, 0xd6, 0x28, 0x6e, 0xab, 0x0c, 0x00, 0xcd,
	0x3a, 0xc5, 0x13, 0x93, 0x11, 0x89, 0xf9, 0x76, 0x3a, 0x31, 0x47, 0xab, 0xf7, 0x53, 0x3c, 0x33,
	0xff, 0x64, 0x00, 0xc5, 0xa5, 0x15, 0x93, 0xeb, 0xf0, 0x93, 0x85, 0x20, 0xeb, 0x1a, 0x4e, 0x34,
	0x87, 0xfc, 0x37, 0xba, 0x81, 0x5d, 0x3a, 0xa6, 0x8c, 0x38, 0x3a, 0xe5, 0x00, 0xdd, 0xe1, 0x08,
	0x19, 0xff, 0xab, 0x85, 0x12, 0x30, 0xc3, 0x5e, 0xeb, 0x72, 0x9a, 0xf8, 0xc1, 0xd9, 0x1a, 0x46,
	0x74, 0xc6, 0x8a, 0x5e, 0x01, 0x32, 0x03, 0xcb, 0x48, 0x04, 0x14, 0x8a, 0xf5, 0xf8, 0x0e, 0x01,
	0x4f, 0x03, 0xcb, 0x48, 0x84, 0x53, 0xcd, 0x84, 0x0d, 0x1d, 0x40, 0xfe, 0xe5, 0x98, 0x11, 0x9d,
	0xda, 0x6f, 0x08, 0x1f, 0xfd, 0x2c, 0xde, 0x0c, 0x0d, 0x5d, 0xfb, 0x0d, 0xa9, 0x5c, 0x02, 0x9a,
	0xbd, 0x35, 0x3a, 0x82, 0x9d, 0xa9, 0xab, 0xe9, 0x51, 0x8d, 0xf2, 0xb8, 0x48, 0x63, 0x8e, 0x4f,
	0xc9, 0x18, 0xed, 0x43, 0xce, 0xbb, 0xba, 0xa2, 0x84, 0xc9, 0x0f, 0xbd, 0x7c, 0xaa, 0x7c, 0x00,
	0xea, 0xe9, 0x9c, 0xab, 0x58, 0x64, 0x64, 0x9b, 0x44, 0xb7, 0x2d, 0x59, 0xf3, 0x4d, 0x61, 0xd0,
	0xac, 0x27, 0x7b, 0x50, 0x9a, 0x0e, 0xca, 0xc6, 0x43, 0x42, 0xab, 0x7f, 0xe5, 0xa0, 0xd0, 0xe5,
	0x19, 0x90, 0x4d, 0xbe, 0x0d, 0x69, 0x89, 0xce, 0xe3, 0xb4, 0x6d, 0x85, 0xf2, 0x2a, 0x3b, 0x8d,
	0xdf, 0x20, 0x8f, 0xa3, 0x47, 0xa4, 0x4d, 0xeb, 0xe8, 0x06, 0xd7, 0xd1, 0xc3, 0x85, 0xf9, 0xe5,
	0x7f, 0x16, 0x08, 0xe9, 0x01, 0xe4, 0x83, 0x61, 0xb4, 0xd1, 0x08, 0x09, 0xda, 0x14, 0x86, 0x0e,
	0x45, 0x97, 0x50, 0x10, 0xba, 0x23, 0xe7, 0x26, 0xcb, 0xe7, 0xe6, 0x93, 0xe5, 0x81, 0xe4, 0xe0,
	0xc4, 0x86, 0x48, 0x8c, 0x8d, 0xe2, 0xc4, 0x06, 0xba, 0x0d, 0x05, 0xc1, 0x29, 0x35, 0x76, 0x7d,
	0xf9, 0x4c, 0xcc, 0x2e, 0x55, 0x58, 0x11, 0x78, 0x21, 0xaa, 0x6d, 0x28, 0xf4, 0xf9, 0x86, 0x24,
	0xe9, 0x36, 0x97, 0xd3, 0xcd, 0x6e, 0x53, 0x58, 0x11, 0x78, 0x41, 0xf7, 0x2b, 0x94, 0x26, 0x6b,
	0x62, 0xb8, 0xb8, 0x48, 0xd6, 0x3c, 0x67, 0xfd, 0xf0, 0xbf, 0xb4, 0x27, 0xb9, 0xea, 0xe0, 0x1d,
	0x27, 0x76, 0x22, 0x22, 0x98, 0x61, 0x23, 0x3a, 0x09, 0x7e, 0xe0, 0xfc, 0x9f, 0xad, 0x32, 0x27,
	0xf3, 0xc2, 0x14, 0x69, 0xdf, 0x99, 0x0a, 0xf2, 0x0c, 0x54, 0x7f, 0xb2, 0x22, 0xc9, 0x18, 0x0a,
	0x8f, 0x51, 0x5b, 0x14, 0x63, 0xfe, 0x4a, 0x85, 0x8b, 0xb7, 0x3c, 0xdc, 0x50, 0x31, 0x41, 0x4d,
	0x16, 0x38, 0x2e, 0x79, 0x79, 0x21, 0x79, 0x5f, 0x4c, 0x4b, 0xde, 0xa3, 0x15, 0x04, 0x37, 0xae,
	0x75, 0xfe, 0xb4, 0xd4, 0xc9, 0xd6, 0xf9, 0x19, 0x76, 0xa7, 0xc7, 0xc9, 0xe7, 0x9a, 0x21, 0x45,
	0xfd, 0x68, 0x75, 0x95, 0xc1, 0x88, 0xce, 0xd8, 0xaa, 0xbf, 0xa7, 0x60, 0x57, 0xee, 0x09, 0xd1,
	0x1b, 0x6b, 0xae, 0x45, 0x5e, 0xa3, 0x73, 0xc8, 0xf1, 0x32, 0x86, 0xeb, 0x5f, 0x66, 0x59, 0x99,
	0xe6, 0xa1, 0x85, 0x51, 0xcc, 0x81, 0xa4, 0xa9, 0x3c, 0x04, 0xb8, 0xb5, 0xce, 0x13, 0xf0, 0x23,
	0x06, 0xc5, 0xc4, 0xca, 0x82, 0x76, 0x60, 0xab, 0x7d, 0xde, 0x68, 0xb6, 0xf4, 0x1f, 0x3b, 0x4f,
	0x3b, 0xe7, 0x3f, 0x75, 0xd4, 0x35, 0x54, 0x04, 0x45, 0x98, 0x70, 0xb3, 0xde, 0x78, 0xa6, 0xa6,
	0xd0, 0x1e, 0xec, 0x44, 0x3e, 0xf5, 0x8b, 0xba, 0xd6, 0xaa, 0x3f, 0x69, 0x35, 0xd5, 0xf4, 0x2d,
	0xb4, 0x75, 0x5e, 0x6f, 0x68, 0x9d, 0xef, 0xd5, 0x0c, 0x2a, 0x41, 0x31, 0xf2, 0x8c, 0x8c, 0xd9,
	0xa3, 0xdf, 0x52, 0xa0, 0x26, 0x25, 0x03, 0x21, 0xd8, 0xee, 0x36, 0xf1, 0x45, 0x13, 0xeb, 0x5a,
	0xe7, 0xa2, 0xde, 0xd2, 0x1a, 0xea, 0x1a, 0x7a, 0x0b, 0x4a, 0x13, 0x9b, 0xd6, 0xd3, 0xea, 0x2d,
	0xed, 0x79, 0xc8, 0x90, 0x42, 0x2a, 0x14, 0xe4, 0x81, 0xb8, 0x52, 0x3a, 0x06, 0x6f, 0x5e, 0x6a,
	0x3d, 0x11, 0xfc, 0x01, 0x1c, 0x48, 0xdb, 0x77, 0x75, 0xad, 0xd5, 0x6c, 0xe8, 0xbd, 0xf3, 0x5b,
	0xa2, 0xa6, 0x0a, 0x2f, 0x73, 0xfc, 0xbf, 0xb3, 0x8f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xa6,
	0x82, 0x6b, 0x68, 0xe0, 0x0d, 0x00, 0x00,
}
