apiVersion: apps/v1
kind: Deployment
metadata:
  name: trtis-model-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trtis-model-simple
  template:
    metadata:
      annotations:
        seldon.io/trtis-model-id: simple
      labels:
        app: trtis-model-simple
    spec:
      schedulerName: trtis-scheduler      
      initContainers:
      - args:
        - gs://seldon-models/trtis/simple-model
        - /mnt/models
        image: gcr.io/kfserving/storage-initializer:0.2.1
        name: model-initializer
        volumeMounts:
        - name: local-repo
          mountPath: /mnt/models
      - name: trtis-loader
        image: seldonio/trtis-loader:0.1
        args: ["--model-src","/mnt/models/simple","--trtis-model-repo","/trtis/$(NODE_NAME)", "--trtis-host" ,"$(NODE_IP)"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: trtis-repo
          mountPath: "/trtis"
        - name: local-repo
          mountPath: "/mnt/models"
      containers:
      - name: model
        image: seldonio/trtis-proxy:0.1
        command: ["/trtis-proxy"]
        args: ["--model-name","simple","--trtis-model-repo","/trtis/$(NODE_NAME)", "--trtis-host" ,"$(NODE_IP)"]
        ports:
        - containerPort: 9000
          protocol: TCP
          name: http
        - containerPort: 9001
          protocol: TCP
          name: grpc
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: trtis-repo
          mountPath: "/trtis"
        resources:
          limits:
            seldon.io/trtis-gpu-mem: 400Mi          
      volumes:	 
      - name: trtis-repo
        persistentVolumeClaim:
          claimName: nfs-pvc
      - name: local-repo
        emptyDir: {}

