apiVersion: v1
kind: Service
metadata:
  name: trtis-svc-demo
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 8001
      targetPort: 8001
  selector:
    app: trtis
  type: LoadBalancer
  
