apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default 
  name: trtis-scheduler 
  labels:
    app: trtis-scheduler 
    component: trtis-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trtis-scheduler
subjects:
- kind: ServiceAccount
  name: trtis-scheduler
  namespace: default 
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:kube-scheduler
